
const GAMES=[
["moto","Moto Rush","action","Corri, salta e vinci!","moto-rush"],
["nihal","Nihal Dino Adventure","special","Salta, raccogli, esplora!","nihal-dino"],
["niha","Niha Rainbow Quest","special","Un mondo magico per Niha!","niha-rainbow"],
["imad","Imad Balloon Adventure","special","Palloncini, animali e divertimento!","imad-balloon"],
["color","Colora il Mondo","creative","Tanti disegni da colorare!","colora-mondo"],
["car","Car Racing","action","Piste e sfide emozionanti!","car-racing"],
["goal","Super Goal","sport","Tira e segna!","super-goal"],
["space","Space Defender","action","Proteggi la galassia!","space-defender"],
["memory","Memory Kids","learning","Trova le coppie!","memory-kids"],
["math","Math Heroes","learning","Impara giocando!","math-heroes"],
["puzzle","Puzzle Animali","learning","Completa il puzzle!","puzzle-animali"],
["piano","Piano Party","creative","Suona e divertiti!","piano-party"],
["drums","Batteria Kids","creative","Diventa un musicista!","batteria-kids"],
["fish","Pesca Felice","adventure","Pesca gli amici del mare!","pesca-felice"],
["cook","Cucina con noi","learning","Prepara piatti deliziosi!","cucina"],
["maze","Labirinto Avventura","adventure","Trova la strada!","labirinto"],
["draw","Impara a Disegnare","creative","Segui e colora!","disegnare"],
["abc","Alfabeto Parlante","learning","Ascolta e impara!","alfabeto"],
["shapes","Forme e Colori","learning","Scopri e gioca!","forme-colori"],
["farm","Fattoria Felice","adventure","Animali e suoni reali!","fattoria"]
].map(x=>({id:x[0],name:x[1],cat:x[2],desc:x[3],cover:x[4]}));

const grid=document.querySelector("#gamesGrid"),overlay=document.querySelector("#gameOverlay"),stage=document.querySelector("#gameStage"),gameTitle=document.querySelector("#gameTitle"),toast=document.querySelector("#toast");
let current=null,cleanup=()=>{},soundOn=true,deferredInstall=null;
const S={coin:new Audio("audio-coin.wav"),win:new Audio("audio-win.wav"),hit:new Audio("audio-hit.wav"),jump:new Audio("audio-jump.wav"),pop:new Audio("audio-pop.wav"),goal:new Audio("audio-goal.wav"),shot:new Audio("audio-shot.wav"),wrong:new Audio("audio-wrong.wav"),bg:new Audio("audio-bg.wav")};
S.bg.loop=true;S.bg.volume=.32;
function snd(n){if(!soundOn||!S[n])return;try{S[n].currentTime=0;S[n].play().catch(()=>{})}catch{}}
function say(t){if(soundOn&&window.speechSynthesis){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="it-IT";u.rate=.92;u.pitch=1.05;speechSynthesis.speak(u)}}
function showToast(t){toast.textContent=t;toast.classList.remove("hidden");setTimeout(()=>toast.classList.add("hidden"),1800)}
function render(cat="all"){grid.innerHTML=GAMES.filter(g=>cat==="all"||g.cat===cat).map(g=>`<article class="gameCard"><img src="cover-${g.cover}.jpg" alt="${g.name}"><span class="tag">${g.cat}</span><div class="info"><h3>${g.name}</h3><p>${g.desc}</p></div><button data-id="${g.id}" aria-label="Gioca a ${g.name}"></button></article>`).join("");grid.querySelectorAll("button[data-id]").forEach(b=>b.addEventListener("click",()=>openGame(b.dataset.id)))}
render();
document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelector(".filters .active")?.classList.remove("active");b.classList.add("active");render(b.dataset.cat)});
document.querySelector("#soundBtn").onclick=()=>{soundOn=!soundOn;document.querySelector("#soundBtn").textContent=soundOn?"🔊":"🔇";if(!soundOn){S.bg.pause();speechSynthesis?.cancel()}else S.bg.play().catch(()=>{})};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e});
document.querySelector("#installBtn").onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}else showToast("iPhone: Condividi → Aggiungi alla schermata Home")};
document.querySelector("#exitBtn").onclick=closeGame;document.querySelector("#restartBtn").onclick=()=>current&&openGame(current);document.querySelector("#fullBtn").onclick=()=>overlay.requestFullscreen?.().catch(()=>showToast("Apri dalla schermata Home per effetto app"));
function closeGame(){cleanup();cleanup=()=>{};overlay.classList.add("hidden");stage.innerHTML="";speechSynthesis?.cancel()}
function openGame(id){cleanup();cleanup=()=>{};current=id;let g=GAMES.find(x=>x.id===id);gameTitle.textContent=g.name;overlay.classList.remove("hidden");stage.innerHTML="";let fn={moto:()=>laneRace("🏍️","Moto Rush",true),car:()=>laneRace("🏎️","Car Racing",false),nihal:dino,niha:rainbow,imad:balloons,color:coloring,goal,space,memory,math,puzzle,piano,drums,fish,cook,maze,draw:trace,abc,shapes,farm}[id];if(fn)fn()}
function shell(withControls=true){stage.innerHTML=`<div class="gameShell"><div class="hud"><span id="score">⭐ 0</span><span id="status">❤️ 3</span></div><canvas class="canvas"></canvas>${withControls?`<div class="touch"><div class="dpad"><button class="up">▲</button><button class="left">◀</button><button class="down">▼</button><button class="right">▶</button></div><button class="fire">⚡</button></div>`:""}</div>`;let box=stage.firstElementChild,c=box.querySelector("canvas"),ctx=c.getContext("2d"),D=Math.min(devicePixelRatio||1,2);function resize(){let r=box.getBoundingClientRect();c.width=Math.max(1,r.width*D);c.height=Math.max(1,r.height*D);ctx.setTransform(D,0,0,D,0,0)}resize();return{box,c,ctx,w:()=>box.clientWidth,h:()=>box.clientHeight}}
function laneRace(hero,title,moto){let {box,ctx,w,h}=shell(true),lane=1,score=0,lives=3,speed=5,objs=[],frame=0,raf=0,alive=true,jump=0;let left=box.querySelector(".left"),right=box.querySelector(".right"),fire=box.querySelector(".fire");left.onclick=()=>lane=Math.max(0,lane-1);right.onclick=()=>lane=Math.min(2,lane+1);fire.textContent=moto?"⬆️":"💨";fire.onclick=()=>{if(moto&&jump<=0){jump=65;snd("jump")}else speed=Math.min(9,speed+.7)};say(title+". Schiva gli ostacoli e raccogli le monete.");
function loop(){if(!alive)return;let W=w(),H=h(),roadW=W*.72,x0=W*.14;ctx.clearRect(0,0,W,H);let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,"#66c7ff");sky.addColorStop(.4,"#bce8ff");sky.addColorStop(.41,"#55a84c");sky.addColorStop(1,"#2f6e35");ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle="#30343b";ctx.fillRect(x0,0,roadW,H);for(let i=1;i<3;i++){ctx.strokeStyle="#fff";ctx.lineWidth=4;ctx.setLineDash([28,28]);ctx.beginPath();ctx.moveTo(x0+i*roadW/3,(frame*speed)%56-56);ctx.lineTo(x0+i*roadW/3,H);ctx.stroke()}ctx.setLineDash([]);if(frame++%Math.max(28,52-Math.floor(score/35))===0)objs.push({lane:Math.floor(Math.random()*3),y:-40,t:Math.random()<.62?"🪙":(moto?"🚧":"🚙")});objs.forEach(o=>o.y+=speed);let hy=H-105-jump; if(jump>0)jump=Math.max(0,jump-4);let hx=x0+(lane+.5)*roadW/3;ctx.textAlign="center";ctx.font="54px serif";ctx.fillText(hero,hx,hy);ctx.font="38px serif";objs.forEach(o=>ctx.fillText(o.t,o.x=x0+(o.lane+.5)*roadW/3,o.y));objs=objs.filter(o=>{if(o.lane===lane&&Math.abs(o.y-hy)<45&&jump<28){if(o.t==="🪙"){score+=10;snd("coin")}else{lives--;snd("hit")}document.querySelector("#score").textContent="⭐ "+score;document.querySelector("#status").textContent="❤️ "+lives;if(lives<=0){alive=false;say("Partita finita. Punteggio "+score);setTimeout(()=>showToast("🏁 Punteggio "+score),100)}return false}if(o.y>H+50){if(o.t!=="🪙")score++;return false}return true});speed=Math.min(8.5,5+score/180);raf=requestAnimationFrame(loop)}loop();cleanup=()=>{alive=false;cancelAnimationFrame(raf)}}
function dino(){let {box,ctx,w,h}=shell(false),y=0,vy=0,score=0,lives=3,stars=[],rocks=[],frame=0,raf,alive=true;box.addEventListener("pointerdown",()=>{if(y===0){vy=15;snd("jump")}});say("Nihal Dino Adventure. Tocca per saltare e raccogli le stelle!");
function loop(){if(!alive)return;let W=w(),H=h(),ground=H-85;ctx.fillStyle="#70d7ff";ctx.fillRect(0,0,W,H);ctx.fillStyle="#7ac94d";ctx.fillRect(0,ground,W,85);for(let i=0;i<10;i++){ctx.fillStyle="#53ae45";ctx.beginPath();ctx.arc((i*120-frame*2)% (W+120),ground,65,Math.PI,0);ctx.fill()}if(frame%70===0)stars.push({x:W+30,y:ground-80-Math.random()*90});if(frame%115===0)rocks.push({x:W+30});frame++;vy-=.8;y=Math.max(0,y+vy);if(y===0&&vy<0)vy=0;ctx.font="58px serif";ctx.textAlign="center";ctx.fillText("🦖",95,ground-y);ctx.font="34px serif";stars.forEach(s=>{s.x-=5;ctx.fillText("⭐",s.x,s.y)});rocks.forEach(r=>{r.x-=5;ctx.fillText("🪨",r.x,ground)});stars=stars.filter(s=>{if(Math.abs(s.x-95)<43&&Math.abs(s.y-(ground-y))<55){score+=10;snd("coin");document.querySelector("#score").textContent="⭐ "+score;return false}return s.x>-40});rocks=rocks.filter(r=>{if(Math.abs(r.x-95)<43&&y<45){lives--;snd("hit");document.querySelector("#status").textContent="❤️ "+lives;if(lives<=0){alive=false;say("Bravo Nihal. Hai raccolto "+score+" punti")}return false}return r.x>-40});raf=requestAnimationFrame(loop)}loop();cleanup=()=>{alive=false;cancelAnimationFrame(raf)}}
function rainbow(){let {box,ctx,w,h}=shell(false),score=0,t=35,stars=[],raf,alive=true,timer;box.style.background="linear-gradient(#8e6cff,#ff9ad2)";say("Niha Rainbow Quest. Tocca le stelle magiche prima che spariscano.");function add(){stars.push({x:40+Math.random()*(w()-80),y:80+Math.random()*(h()-150),r:28,born:performance.now()})}for(let i=0;i<5;i++)add();box.onclick=e=>{let r=box.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let j=stars.findIndex(s=>Math.hypot(s.x-x,s.y-y)<40);if(j>=0){stars.splice(j,1);add();score+=10;snd("coin");document.querySelector("#score").textContent="⭐ "+score}};function loop(){if(!alive)return;let W=w(),H=h();let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,"#704cf1");g.addColorStop(.5,"#ff77b9");g.addColorStop(1,"#61d6ff");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.font="40px serif";ctx.textAlign="center";stars.forEach(s=>ctx.fillText("⭐",s.x,s.y));ctx.font="62px serif";ctx.fillText("🦄",W/2,H-80);raf=requestAnimationFrame(loop)}loop();timer=setInterval(()=>{t--;document.querySelector("#status").textContent="⏱ "+t;if(t<=0){clearInterval(timer);alive=false;cancelAnimationFrame(raf);snd("win");say("Bravissima Niha. Hai fatto "+score+" punti!")}},1000);cleanup=()=>{alive=false;cancelAnimationFrame(raf);clearInterval(timer)}}
function balloons(){let t=40,score=0,ints=[],alive=true;stage.innerHTML=`<div class="gameShell" id="balloonBox" style="background:linear-gradient(#6ed9ff,#d6f4ff 60%,#7ed05e)"><div class="hud"><span id="score">🎈 0</span><span id="status">⏱ 40</span></div></div>`;let b=document.querySelector("#balloonBox");say("Imad Balloon Adventure. Scoppia i palloncini e prendi le stelle!");function spawn(){if(!alive)return;let x=document.createElement("button"),bonus=Math.random()<.13;x.textContent=bonus?"⭐":"🎈";x.style.cssText=`position:absolute;left:${5+Math.random()*85}%;bottom:-80px;font-size:${45+Math.random()*30}px;background:none;border:0;transition:transform 3.2s linear`;x.onclick=()=>{score+=bonus?5:1;snd("pop");document.querySelector("#score").textContent="🎈 "+score;x.remove()};b.appendChild(x);requestAnimationFrame(()=>x.style.transform=`translateY(-${b.clientHeight+120}px)`);setTimeout(()=>x.remove(),3300)}ints.push(setInterval(spawn,330));ints.push(setInterval(()=>{t--;document.querySelector("#status").textContent="⏱ "+t;if(t<=0){alive=false;ints.forEach(clearInterval);snd("win");say("Bravo Imad. Hai fatto "+score+" punti!")}},1000));cleanup=()=>{alive=false;ints.forEach(clearInterval)}}
function coloring(){let subjects=["🐶","🐱","🦁","🐘","🐼","🦋","🐢","🐠","🦕","🌻","🌳","🍄","🏡","🌈"];stage.innerHTML=`<div class="panel"><h2>🎨 Colora il Mondo</h2><div class="subjectBar">${subjects.map(x=>`<button>${x}</button>`).join("")}</div><div class="palette"></div><canvas class="drawing" width="900" height="620"></canvas><p>Scegli un disegno, poi colora con il dito.</p></div>`;let c=stage.querySelector("canvas"),x=c.getContext("2d"),subject="🐶",col="#ff4b63",down=false;["#ff4b63","#ff9f1c","#ffd60a","#43d17a","#36c5f0","#4878ff","#9d4edd","#7b4b2a","#111827","#ffffff"].forEach(v=>{let b=document.createElement("button");b.style.background=v;b.onclick=()=>col=v;stage.querySelector(".palette").appendChild(b)});function base(){x.globalCompositeOperation="source-over";x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.fillStyle="#d5d9e1";x.font="330px serif";x.textAlign="center";x.textBaseline="middle";x.fillText(subject,c.width/2,c.height/2);x.globalCompositeOperation="source-atop"}base();stage.querySelectorAll(".subjectBar button").forEach(b=>b.onclick=()=>{subject=b.textContent;base()});function p(e){let r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]}c.onpointerdown=e=>{down=true;c.setPointerCapture?.(e.pointerId);let q=p(e);x.beginPath();x.moveTo(...q)};c.onpointermove=e=>{if(!down)return;let q=p(e);x.strokeStyle=col;x.lineWidth=42;x.lineCap="round";x.lineTo(...q);x.stroke()};c.onpointerup=()=>down=false;cleanup=()=>{}}
function goal(){stage.innerHTML=`<div class="panel"><h2>⚽ Super Goal</h2><div id="pitch" style="height:min(58vh,480px);position:relative;border-radius:18px;background:linear-gradient(#34b35c,#13803c);overflow:hidden"><div style="position:absolute;left:15%;right:15%;top:28px;height:155px;border:9px solid #fff;border-bottom:0"></div><div id="keeper" style="position:absolute;top:110px;left:46%;font-size:60px">🧤</div><div style="position:absolute;bottom:25px;left:46%;font-size:62px">⚽</div></div><div class="message">Tocca dentro la porta per tirare</div></div>`;let p=stage.querySelector("#pitch"),k=stage.querySelector("#keeper"),score=0,dir=1,pos=45,raf,alive=true;function mv(){if(!alive)return;pos+=dir*.8;if(pos>70||pos<20)dir*=-1;k.style.left=pos+"%";raf=requestAnimationFrame(mv)}mv();p.onclick=e=>{let r=p.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;if(y>43||x<15||x>85)return;if(Math.abs(x-pos)<12){snd("wrong");stage.querySelector(".message").textContent="🧤 Parata!"}else{score++;snd("goal");say("Goal!");stage.querySelector(".message").textContent="⚽ GOOOL! "+score}};cleanup=()=>{alive=false;cancelAnimationFrame(raf)}}
function space(){let {box,ctx,w,h}=shell(false),ship={x:w()/2,y:h()-80},rocks=[],shots=[],score=0,lives=3,frame=0,raf,alive=true;box.onpointermove=e=>{let r=box.getBoundingClientRect();ship.x=e.clientX-r.left};box.onpointerdown=e=>{shots.push({x:ship.x,y:ship.y-25});snd("shot")};say("Space Defender. Muovi la navicella e tocca per sparare.");function loop(){if(!alive)return;let W=w(),H=h();ctx.fillStyle="#020617";ctx.fillRect(0,0,W,H);for(let i=0;i<60;i++){ctx.fillStyle="#fff";ctx.fillRect((i*97)%W,(i*53+frame)%H,2,2)}if(frame++%38===0)rocks.push({x:30+Math.random()*(W-60),y:-35});shots.forEach(s=>s.y-=9);rocks.forEach(r=>r.y+=4.2);ctx.font="52px serif";ctx.textAlign="center";ctx.fillText("🚀",ship.x,ship.y);ctx.font="37px serif";rocks.forEach(r=>ctx.fillText("☄️",r.x,r.y));ctx.fillStyle="#6cf";shots.forEach(s=>ctx.fillRect(s.x-2,s.y,4,16));rocks=rocks.filter(r=>{let hit=shots.find(s=>Math.hypot(s.x-r.x,s.y-r.y)<30);if(hit){shots.splice(shots.indexOf(hit),1);score+=10;snd("coin");document.querySelector("#score").textContent="⭐ "+score;return false}if(r.y>H-45){lives--;snd("hit");document.querySelector("#status").textContent="❤️ "+lives;if(lives<=0){alive=false;say("Missione terminata. "+score+" punti")}return false}return true});shots=shots.filter(s=>s.y>-30);raf=requestAnimationFrame(loop)}loop();cleanup=()=>{alive=false;cancelAnimationFrame(raf)}}
function memory(){let level=1;function build(){let pairs=Math.min(8,2+level),icons=["🐶","🐱","🦁","🐸","🐼","🦊","🐵","🐯"].slice(0,pairs),arr=[...icons,...icons].sort(()=>Math.random()-.5),open=[],done=0;stage.innerHTML=`<div class="panel"><h2>🧠 Memory Kids</h2><p>Livello ${level}</p><div class="board memory">${arr.map(v=>`<button data-v="${v}">❓</button>`).join("")}</div><div class="message">Trova tutte le coppie</div></div>`;stage.querySelectorAll(".memory button").forEach(b=>b.onclick=()=>{if(open.length===2||b.dataset.ok)return;b.textContent=b.dataset.v;open.push(b);if(open.length===2)setTimeout(()=>{if(open[0].dataset.v===open[1].dataset.v){open.forEach(q=>q.dataset.ok="1");done+=2;snd("coin");if(done===arr.length){snd("win");say("Bravissimo. Livello successivo");level++;setTimeout(build,700)}}else{snd("wrong");open.forEach(q=>q.textContent="❓")}open=[]},500)})}build();cleanup=()=>{}}
function math(){let score=0,streak=0,level=1;function q(){let max=level<3?10:20,a=1+Math.floor(Math.random()*max),b=1+Math.floor(Math.random()*max),op=level<2?"+":Math.random()<.5?"+":"−",ans=op==="+"?a+b:Math.abs(a-b);if(op==="−"&&b>a)[a,b]=[b,a];let opts=[ans,ans+1,Math.max(0,ans-1)].sort(()=>Math.random()-.5);stage.innerHTML=`<div class="panel"><h2>🔢 Math Heroes</h2><div class="message">⭐ ${score} &nbsp; 🔥 ${streak}</div><h2 style="font-size:58px">${a} ${op} ${b} = ?</h2><div class="choices">${opts.map(o=>`<button class="choice">${o}</button>`).join("")}</div></div>`;stage.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{if(+b.textContent===ans){score+=10;streak++;if(streak%5===0)level++;snd("coin");say("Giusto!")}else{streak=0;snd("wrong");say("Riprova")}setTimeout(q,330)})}q();cleanup=()=>{}}
function puzzle(){let order=[0,1,2,3,4,5,6,7,8],empty=8,moves=0;do{order.sort(()=>Math.random()-.5);empty=order.indexOf(8)}while(order.every((v,i)=>v===i));function draw(){stage.innerHTML=`<div class="panel"><h2>🧩 Puzzle Animali</h2><p>Mosse: ${moves}</p><div id="puz" style="display:grid;grid-template-columns:repeat(3,1fr);gap:5px;max-width:480px;margin:auto">${order.map((v,i)=>v===8?`<button data-i="${i}" style="aspect-ratio:1;background:#07182d;border:0;border-radius:12px"></button>`:`<button data-i="${i}" style="aspect-ratio:1;background:url('cover-puzzle-animali.jpg') ${(v%3)*50}% ${Math.floor(v/3)*50}%/300% 300%;border:0;border-radius:12px"></button>`).join("")}</div><div class="message">Ricostruisci il leone</div></div>`;stage.querySelectorAll("#puz button").forEach(b=>b.onclick=()=>move(+b.dataset.i))}function move(i){let a=Math.floor(i/3),b=i%3,c=Math.floor(empty/3),d=empty%3;if(Math.abs(a-c)+Math.abs(b-d)===1){[order[i],order[empty]]=[order[empty],order[i]];empty=i;moves++;snd("jump");draw();if(order.every((v,i)=>v===i)){snd("win");say("Puzzle completato!")}}}draw();cleanup=()=>{}}
function piano(){let notes=[["DO",261.63],["RE",293.66],["MI",329.63],["FA",349.23],["SOL",392],["LA",440],["SI",493.88]],ctxA=null;function note(f){if(!soundOn)return;ctxA??=new(window.AudioContext||window.webkitAudioContext)();let o=ctxA.createOscillator(),g=ctxA.createGain();o.frequency.value=f;o.type="triangle";g.gain.value=.18;o.connect(g);g.connect(ctxA.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctxA.currentTime+.55);o.stop(ctxA.currentTime+.56)}stage.innerHTML=`<div class="panel"><h2>🎹 Piano Party</h2><div class="piano">${notes.map((n,i)=>`<button data-i="${i}">${n[0]}</button>`).join("")}</div><div class="message">Suona la tua musica!</div></div>`;stage.querySelectorAll(".piano button").forEach(b=>b.onclick=()=>{note(notes[+b.dataset.i][1]);b.animate([{transform:"translateY(0)"},{transform:"translateY(8px)"}],{duration:120})});cleanup=()=>ctxA?.close()}
function drums(){stage.innerHTML=`<div class="panel"><h2>🥁 Batteria Kids</h2><div class="drums">${["🥁","🪘","🔔","👏","💥","🎵"].map((x,i)=>`<button data-i="${i}">${x}</button>`).join("")}</div><div class="message">Crea il tuo ritmo!</div></div>`;let freqs=[120,180,620,430,90,780];stage.querySelectorAll(".drums button").forEach(b=>b.onclick=()=>{let ac=new(window.AudioContext||window.webkitAudioContext)(),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freqs[+b.dataset.i];o.type=+b.dataset.i<3?"square":"sine";g.gain.value=.16;o.connect(g);g.connect(ac.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.2);o.stop(ac.currentTime+.21);b.animate([{transform:"scale(1)"},{transform:"scale(.88)"}],{duration:100})});cleanup=()=>{}}
function fish(){let {box,ctx,w,h}=shell(false),hookX=w()/2,hookY=80,down=false,fishies=[],score=0,raf,alive=true,frame=0;box.onclick=()=>{down=!down;snd("jump")};say("Pesca Felice. Tocca per calare o tirare su l'amo.");function loop(){if(!alive)return;let W=w(),H=h();ctx.fillStyle="#68d7ff";ctx.fillRect(0,0,W,75);ctx.fillStyle="#137ac1";ctx.fillRect(0,75,W,H-75);if(frame++%80===0)fishies.push({x:-50,y:130+Math.random()*(H-220),v:2+Math.random()*2,e:Math.random()<.5?"🐠":"🐟"});fishies.forEach(f=>f.x+=f.v);hookY+=down?5:-5;hookY=Math.max(80,Math.min(H-50,hookY));ctx.strokeStyle="#eee";ctx.beginPath();ctx.moveTo(hookX,0);ctx.lineTo(hookX,hookY);ctx.stroke();ctx.font="26px serif";ctx.textAlign="center";ctx.fillText("🪝",hookX,hookY);ctx.font="38px serif";fishies.forEach(f=>ctx.fillText(f.e,f.x,f.y));fishies=fishies.filter(f=>{if(Math.abs(f.x-hookX)<32&&Math.abs(f.y-hookY)<30){score+=10;snd("coin");document.querySelector("#score").textContent="🐟 "+score;down=false;return false}return f.x<W+60});raf=requestAnimationFrame(loop)}loop();cleanup=()=>{alive=false;cancelAnimationFrame(raf)}}
function cook(){let recipes=[["🍕","🍅","🧀","🔥"],["🥪","🍞","🥬","🧀"],["🥗","🥬","🍅","🥕"],["🍰","🥚","🥛","🍓"]],r=recipes[Math.floor(Math.random()*recipes.length)],step=0,score=0;let all=["🍅","🧀","🔥","🍞","🥬","🥕","🥚","🥛","🍓"];function draw(){stage.innerHTML=`<div class="panel"><h2>👨‍🍳 Cucina con noi</h2><div style="font-size:65px">${r[0]}</div><p>Segui la ricetta nell'ordine giusto</p><div class="recipe">${all.sort(()=>Math.random()-.5).slice(0,7).map(x=>`<button>${x}</button>`).join("")}</div><div class="message">Passo ${step+1}: scegli ${r[step]||"✅"}</div></div>`;stage.querySelectorAll(".recipe button").forEach(b=>b.onclick=()=>{if(b.textContent===r[step]){step++;score+=10;snd("coin");say("Perfetto");if(step===r.length){snd("win");say("Piatto pronto!");stage.querySelector(".message").textContent="🎉 Piatto pronto!";return}draw()}else{snd("wrong");say("Prova un altro ingrediente")}})}draw();cleanup=()=>{}}
function maze(){let map=[
"########","#......#","#.####.#","#....#.#","####.#.#","#....#.#","#.####.#","#......#"].map(x=>x.split("")),p={r:1,c:1},goal={r:6,c:6};function draw(){stage.innerHTML=`<div class="panel"><h2>🦔 Labirinto Avventura</h2><div class="maze">${map.flatMap((row,r)=>row.map((v,c)=>`<div style="background:${v==="#"?"#17466f":"#8ed46a"}">${r===p.r&&c===p.c?"🦔":r===goal.r&&c===goal.c?"🏁":""}</div>`)).join("")}</div><div class="choices" style="margin-top:12px"><button class="choice" data-d="u">▲</button><button class="choice" data-d="l">◀</button><button class="choice" data-d="r">▶</button></div></div>`;stage.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>move(b.dataset.d))}function move(d){let nr=p.r+(d==="u"?-1:0),nc=p.c+(d==="l"?-1:d==="r"?1:0);if(map[nr]?.[nc]==="."){p={r:nr,c:nc};snd("jump");draw();if(p.r===goal.r&&p.c===goal.c){snd("win");say("Hai trovato la strada!")}}}draw();cleanup=()=>{}}
function trace(){let shapes=["★","♥","●","▲","☀"],idx=0,down=false;stage.innerHTML=`<div class="panel"><h2>✏️ Impara a Disegnare</h2><canvas class="drawing" width="900" height="620"></canvas><div class="choices">${shapes.map((s,i)=>`<button class="choice" data-i="${i}">${s}</button>`).join("")}</div><p>Segui il contorno con il dito.</p></div>`;let c=stage.querySelector("canvas"),x=c.getContext("2d");function base(){x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.strokeStyle="#c7cbd4";x.lineWidth=10;x.setLineDash([16,16]);x.font="360px serif";x.textAlign="center";x.textBaseline="middle";x.strokeText(shapes[idx],c.width/2,c.height/2);x.setLineDash([])}base();stage.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>{idx=+b.dataset.i;base()});function p(e){let r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]}c.onpointerdown=e=>{down=true;let q=p(e);x.beginPath();x.moveTo(...q)};c.onpointermove=e=>{if(!down)return;let q=p(e);x.strokeStyle="#4d7dff";x.lineWidth=16;x.lineCap="round";x.lineTo(...q);x.stroke()};c.onpointerup=()=>down=false;cleanup=()=>{}}
function abc(){let letters="ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");stage.innerHTML=`<div class="panel"><h2>🔊 Alfabeto Parlante</h2><div class="alphabet">${letters.map(l=>`<button>${l}</button>`).join("")}</div><div class="message">Tocca una lettera</div></div>`;let words={A:"A come albero",B:"B come balena",C:"C come casa",D:"D come dinosauro",E:"E come elefante",F:"F come fiore",G:"G come gatto",M:"M come moto",N:"N come nave",P:"P come palla",S:"S come sole"};stage.querySelectorAll(".alphabet button").forEach(b=>b.onclick=()=>{say(words[b.textContent]||b.textContent);snd("coin");stage.querySelector(".message").textContent=words[b.textContent]||b.textContent});cleanup=()=>{}}
function shapes(){let qs=[["🔴","Cerchio rosso",["🔴","🟦","🟨"]],["🟦","Quadrato blu",["🟩","🟦","🔺"]],["🔺","Triangolo",["🟣","🔺","🟧"]],["⭐","Stella",["❤️","⭐","🟢"]]],i=0,score=0;function q(){let z=qs[i%qs.length];stage.innerHTML=`<div class="panel"><h2>🔷 Forme e Colori</h2><div class="message">Trova: ${z[1]}</div><div class="choices">${z[2].sort(()=>Math.random()-.5).map(x=>`<button class="choice" style="font-size:50px">${x}</button>`).join("")}</div><p>⭐ ${score}</p></div>`;say("Trova "+z[1]);stage.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{if(b.textContent===z[0]){score+=10;i++;snd("coin");say("Bravissimo");setTimeout(q,350)}else{snd("wrong");say("Riprova")}})}q();cleanup=()=>{}}
function farm(){let animals=[["🐄","mucca","Muu"],["🐔","gallina","Coccodè"],["🐷","maialino","Oink oink"],["🐑","pecora","Bee"],["🐴","cavallo","Ih ih"],["🐶","cane","Bau bau"]],score=0;stage.innerHTML=`<div class="panel"><h2>🐄 Fattoria Felice</h2><p>Tocca gli animali, ascolta il loro verso e dagli da mangiare.</p><div class="choices">${animals.map(a=>`<button class="choice" data-n="${a[1]}" data-s="${a[2]}" style="font-size:50px">${a[0]}</button>`).join("")}</div><div class="message">🥕 Cibo: <b id="food">0</b></div></div>`;stage.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{score++;snd("coin");say(b.dataset.n+". "+b.dataset.s);document.querySelector("#food").textContent=score});cleanup=()=>{}}
