'use strict';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
const games=[
 {id:'colors',name:'Trova il colore',icon:'🎨',desc:'Ascolta il colore e tocca quello giusto.',age:'3-5',glow:'#ff5f91'},
 {id:'shapes',name:'Forme magiche',icon:'🔺',desc:'Abbina cerchio, quadrato, stella e triangolo.',age:'3-5',glow:'#8c61ff'},
 {id:'count',name:'Conta gli amici',icon:'🐥',desc:'Conta gli animaletti e scegli il numero corretto.',age:'3-5',glow:'#ffc83d'},
 {id:'balloons',name:'Scoppia palloncini',icon:'🎈',desc:'Tocca i palloncini prima che volino via.',age:'3-5',glow:'#35db7a'},
 {id:'memory',name:'Memory animali',icon:'🧠',desc:'Trova tutte le coppie di animali.',age:'3-8',glow:'#a45bff'},
 {id:'whack',name:'Acchiappa la talpa',icon:'🐹',desc:'La talpa compare veloce: prendila!',age:'3-8',glow:'#ef8b3a'},
 {id:'catch',name:'Prendi le stelle',icon:'⭐',desc:'Muovi il cestino e raccogli più stelle possibile.',age:'3-8',glow:'#24b7ff'},
 {id:'draw',name:'Disegna libero',icon:'🖍️',desc:'Disegna con il dito e crea quello che vuoi.',age:'3-10',glow:'#ff6da8'},
 {id:'math',name:'Matematica sprint',icon:'➕',desc:'Addizioni e sottrazioni adatte ai bambini.',age:'6-10',glow:'#2bcf88'},
 {id:'tris',name:'Tris',icon:'❌',desc:'Gioca contro un amico o contro il computer.',age:'6-10',glow:'#28a5ff'},
 {id:'maze',name:'Labirinto',icon:'🧩',desc:'Porta il personaggio fino alla bandierina.',age:'6-10',glow:'#f2aa2c'},
 {id:'snake',name:'Snake',icon:'🐍',desc:'Mangia le mele e diventa sempre più lungo.',age:'6-10',glow:'#29cf69'},
 {id:'2048',name:'2048 Junior',icon:'🔢',desc:'Unisci i numeri uguali e crea numeri più grandi.',age:'9-10',glow:'#f29b38'},
 {id:'brick',name:'Brick Breaker',icon:'🧱',desc:'Muovi la racchetta e rompi tutti i mattoni.',age:'6-10',glow:'#ff5277'},
 {id:'race',name:'Mini Car Race',icon:'🏎️',desc:'Cambia corsia e schiva le altre auto.',age:'6-10',glow:'#1ed5d5'},
 {id:'quiz',name:'Quiz bambini',icon:'❓',desc:'Domande semplici su animali, numeri e mondo.',age:'6-10',glow:'#7f68ff'},
 {id:'moto',name:'Moto Sprint',icon:'🏍️',desc:'Corri in moto, cambia corsia, prendi monete e schiva il traffico.',age:'6-10',glow:'#ff6b35',new:true},
 {id:'coloring',name:'Colora animali & natura',icon:'🦋',desc:'Tante pagine da colorare: animali, fiori, piante, casa e dinosauro.',age:'3-10',glow:'#ff70b7',new:true},
 {id:'piano',name:'Piano magico',icon:'🎹',desc:'Suona note vere, prova melodie e ascolta i tasti.',age:'3-10',glow:'#8a7dff',new:true},
 {id:'drums',name:'Batteria Kids',icon:'🥁',desc:'Suona cassa, rullante, tom e piatti con suoni diversi.',age:'3-10',glow:'#f05d5e',new:true},
 {id:'simon',name:'Simon dei colori',icon:'🟢',desc:'Guarda e ascolta la sequenza, poi ripetila senza sbagliare.',age:'6-10',glow:'#35cc88',new:true},
 {id:'alphabet',name:'Alfabeto parlante',icon:'🔤',desc:'Tocca le lettere: la voce pronuncia lettera e parola.',age:'3-8',glow:'#38a7ff',new:true},
 {id:'words',name:'Costruisci la parola',icon:'🧩',desc:'Metti le lettere nel posto giusto e completa parole semplici.',age:'6-10',glow:'#f6b83f',new:true},
 {id:'fishing',name:'Pesca felice',icon:'🎣',desc:'Muovi l’amo, prendi i pesci e evita gli stivali.',age:'3-8',glow:'#2cc8c8',new:true},
 {id:'dino',name:'Dino Jump',icon:'🦖',desc:'Tocca per saltare cactus e raccogliere uova.',age:'6-10',glow:'#61c454',new:true},
 {id:'space',name:'Avventura spaziale',icon:'🚀',desc:'Pilota il razzo, schiva asteroidi e raccogli stelle.',age:'6-10',glow:'#665bff',new:true},
 {id:'basket',name:'Basket Shot',icon:'🏀',desc:'Scegli la potenza giusta e fai più canestri possibile.',age:'6-10',glow:'#ff8a30',new:true},
 {id:'penalty',name:'Calci di rigore',icon:'⚽',desc:'Scegli l’angolo e prova a battere il portiere.',age:'6-10',glow:'#25c66f',new:true},
 {id:'puzzle',name:'Puzzle animali',icon:'🧩',desc:'Ricostruisci animali con tessere da spostare.',age:'3-8',glow:'#a967ff',new:true},
 {id:'bubbles',name:'Bolle dei numeri',icon:'🫧',desc:'Scoppia solo la bolla col numero chiamato dalla voce.',age:'3-8',glow:'#32b9ff',new:true},
 {id:'niha',name:'Niha • Rainbow Stars',icon:'🌈',desc:'Un’avventura colorata fatta apposta per Niha.',age:'3-10',glow:'#ff66aa',new:true},
 {id:'nihal',name:'Nihal • Dino Adventure',icon:'🦕',desc:'Una corsa con dinosauri fatta apposta per Nihal.',age:'3-10',glow:'#43c36f',new:true},
 {id:'imad',name:'Imad • Balloon Party',icon:'🎈',desc:'Una festa di palloncini fatta apposta per Imad.',age:'3-10',glow:'#3ba6ff',new:true}
];
const grid=$('#gameGrid'),dlg=$('#gameDialog'),area=$('#gameArea'),title=$('#gameTitle'),ageLabel=$('#gameAge');
let activeGame=null,cleanup=()=>{},deferredPrompt=null;
function best(id){return store.get('bt_best_'+id,0)} function saveBest(id,n){if(n>best(id))store.set('bt_best_'+id,n)}
function renderCards(filter='all'){grid.innerHTML='';games.filter(g=>filter==='all'||g.age.includes(filter)||g.age===filter||(filter==='3-5'&&g.age==='3-8')||(filter==='6-8'&&['3-8','6-10'].includes(g.age))||(filter==='9-10'&&['6-10','9-10','3-10'].includes(g.age))).forEach(g=>{const c=document.createElement('article');c.className='gameCard';c.style.setProperty('--cardGlow',g.glow);c.innerHTML=`${g.new?'<span class="newTag">NUOVO</span>':''}<div class="gameIcon">${g.icon}</div><span class="ageTag">${g.age.replace('-', '–')} ANNI</span><h3>${g.name}</h3><p>${g.desc}</p><button class="playBtn">▶ Gioca</button>`;$('.playBtn',c).addEventListener('click',()=>openGame(g));grid.append(c)})}
renderCards();
$$('.chip').forEach(b=>b.addEventListener('click',()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCards(b.dataset.age)}));
$('#startBtn').addEventListener('click',()=>$('#gamesSection').scrollIntoView({behavior:'smooth'}));
$('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('light');const light=document.body.classList.contains('light');$('#themeBtn').textContent=light?'🌙':'☀️';store.set('bt_theme',light?'light':'dark')});
if(store.get('bt_theme','dark')==='light'){document.body.classList.add('light');$('#themeBtn').textContent='🌙'}
function closeGame(){cleanup();cleanup=()=>{};try{speechSynthesis.cancel()}catch{};activeGame=null;document.body.classList.remove('game-open');if(document.fullscreenElement&&document.exitFullscreen)document.exitFullscreen().catch(()=>{});if(dlg.open)dlg.close()}
$('#closeGame').addEventListener('click',closeGame);$('#restartGame').addEventListener('click',()=>activeGame&&openGame(activeGame,true));dlg.addEventListener('cancel',e=>{e.preventDefault();closeGame()});
function openGame(g,restart=false){cleanup();cleanup=()=>{};activeGame=g;title.textContent=g.name;ageLabel.textContent=`${g.age.replace('-','–')} anni • schermo intero`;area.innerHTML='';if(!restart&&!dlg.open)dlg.showModal();document.body.classList.add('game-open');if(!restart&&dlg.requestFullscreen&&!document.fullscreenElement){try{const p=dlg.requestFullscreen();if(p&&p.catch)p.catch(()=>{})}catch{}}const fn=({colors,shapes,count,balloons,memory,whack,catch:catchStars,draw,math,tris,maze,snake,'2048':game2048,brick,race,quiz,moto,coloring,piano,drums,simon,alphabet,words,fishing,dino,space,basket,penalty,puzzle,bubbles,niha,nihal,imad}[g.id]);if(fn)fn();else area.innerHTML='<div class="bigPrompt">Gioco non disponibile</div>';unlockAudio();sfx('start');if(!restart)voice(g.name)}
function hud(score=0,label='Punti'){return `<div class="gameHud"><span class="hudPill">${label}: <b id="score">${score}</b></span><span class="hudPill">Record: <b>${best(activeGame.id)}</b></span></div>`}
let soundOn=store.get('bt_sound',true),audioCtx=null;
function unlockAudio(){if(!soundOn)return;try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}catch{}}
function tone(freq=440,dur=.09,type='sine',gain=.06,delay=0){if(!soundOn)return;unlockAudio();if(!audioCtx)return;try{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+dur+.03)}catch{}}
function sfx(kind='tap'){if(!soundOn)return;const seq={tap:[[360,.045,'sine',.035]],start:[[440,.06],[660,.08,'sine',.05,.06]],good:[[523,.08],[659,.08,'sine',.05,.07],[784,.12,'sine',.05,.14]],bad:[[180,.13,'sawtooth',.035]],coin:[[880,.05],[1174,.08,'square',.035,.05]],pop:[[520,.04,'square',.03],[260,.06,'sine',.02,.04]],jump:[[300,.05],[520,.08,'sine',.035,.04]],goal:[[659,.08],[784,.08,'sine',.05,.07],[988,.18,'sine',.05,.14]]}[kind]||[[360,.05]];seq.forEach(x=>tone(...x))}
function voice(text){if(!soundOn)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='it-IT';u.rate=.9;u.pitch=1.08;u.volume=.95;speechSynthesis.speak(u)}catch{}}
const soundBtn=$('#soundBtn');function refreshSound(){if(soundBtn)soundBtn.textContent=soundOn?'🔊':'🔇'}refreshSound();soundBtn?.addEventListener('click',()=>{soundOn=!soundOn;store.set('bt_sound',soundOn);refreshSound();if(soundOn){unlockAudio();sfx('good');voice('Suoni attivati')}else try{speechSynthesis.cancel()}catch{}});area.addEventListener('click',e=>{if(e.target.closest('button')&&soundOn)sfx('tap')});
function colors(){const cols=[['Rosso','#ed4b50'],['Blu','#2788ff'],['Verde','#31c86a'],['Giallo','#ffd236'],['Viola','#8c58dd'],['Arancione','#ff9138']];let score=0,round=0,target=null;area.innerHTML=hud()+`<div class="bigPrompt" id="prompt"></div><div class="colorPad" id="sample"></div><div class="gameButtons" id="answers"></div><div class="result" id="result"></div>`;const next=()=>{round++;if(round>10){saveBest('colors',score);$('#prompt').textContent=`Bravissimo! ${score}/10`;$('#answers').innerHTML='';$('#sample').textContent='🏆';return}target=cols[Math.floor(Math.random()*cols.length)];$('#prompt').textContent=`Trova: ${target[0]}`;$('#sample').style.background=target[1];$('#sample').textContent='';voice(target[0]);const picks=[target,...cols.filter(x=>x!==target).sort(()=>Math.random()-.5).slice(0,2)].sort(()=>Math.random()-.5);$('#answers').innerHTML='';picks.forEach(c=>{const b=document.createElement('button');b.className='choice';b.textContent=c[0];b.style.borderBottom=`8px solid ${c[1]}`;b.addEventListener('click',()=>{if(c===target){score++;$('#score').textContent=score;$('#result').textContent='✅ Giusto!'}else $('#result').textContent=`😊 Era ${target[0]}`;setTimeout(()=>{$('#result').textContent='';next()},550)});$('#answers').append(b)})};next()}
function shapes(){const items=[['Cerchio','●'],['Quadrato','■'],['Triangolo','▲'],['Stella','★'],['Cuore','♥']];let score=0,round=0;area.innerHTML=hud()+`<div class="bigPrompt" id="prompt"></div><div style="font-size:100px;margin:14px" id="shapeShow"></div><div class="gameButtons" id="answers"></div><div class="result" id="result"></div>`;const next=()=>{if(++round>10){saveBest('shapes',score);$('#prompt').textContent=`Hai fatto ${score}/10!`;$('#answers').innerHTML='';return}const t=items[Math.floor(Math.random()*items.length)];$('#prompt').textContent='Che forma è?';$('#shapeShow').textContent=t[1];voice('Che forma è?');$('#answers').innerHTML='';items.sort(()=>Math.random()-.5).slice(0,3).concat([t]).filter((v,i,a)=>a.indexOf(v)===i).slice(0,3).sort(()=>Math.random()-.5).forEach(x=>{const b=document.createElement('button');b.textContent=x[0];b.addEventListener('click',()=>{if(x===t){score++;$('#score').textContent=score;$('#result').textContent='✅ Bravo!'}else $('#result').textContent=`Era ${t[0]}`;setTimeout(()=>{$('#result').textContent='';next()},500)});$('#answers').append(b)})};next()}
function count(){const animals=['🐥','🐶','🐱','🐸','🐰'];let score=0,round=0;area.innerHTML=hud()+`<div class="bigPrompt">Quanti sono?</div><div id="animals" style="font-size:44px;line-height:1.5;max-width:520px;margin:auto"></div><div class="numberGrid" id="answers"></div><div class="result" id="result"></div>`;const next=()=>{if(++round>10){saveBest('count',score);$('#animals').textContent='🏆';$('#answers').innerHTML='';return}const n=1+Math.floor(Math.random()*9),a=animals[Math.floor(Math.random()*animals.length)];$('#animals').textContent=Array(n).fill(a).join(' ');let nums=new Set([n]);while(nums.size<3)nums.add(Math.max(1,Math.min(10,n+Math.floor(Math.random()*5)-2)));$('#answers').innerHTML='';[...nums].sort(()=>Math.random()-.5).forEach(v=>{const b=document.createElement('button');b.className='numberBtn';b.textContent=v;b.addEventListener('click',()=>{if(v===n){score++;$('#score').textContent=score;$('#result').textContent='✅ Esatto!'}else $('#result').textContent=`Sono ${n}`;setTimeout(()=>{$('#result').textContent='';next()},450)});$('#answers').append(b)})};next()}
function balloons(){let score=0,time=20,timer,spawn;area.innerHTML=hud()+`<div class="hudPill" style="display:inline-block">Tempo: <b id="time">20</b>s</div><div id="field" style="position:relative;height:340px;overflow:hidden;border-radius:20px;background:linear-gradient(#a9e4ff,#eefaff);margin-top:12px"></div>`;const field=$('#field');function add(){const b=document.createElement('button');b.textContent='🎈';b.style.cssText=`position:absolute;left:${Math.random()*80+5}%;top:${Math.random()*75+5}%;font-size:${35+Math.random()*25}px;background:transparent;border:0;padding:0`;b.addEventListener('click',()=>{score++;$('#score').textContent=score;b.textContent='✨';setTimeout(()=>b.remove(),120)});field.append(b);setTimeout(()=>b.remove(),1800)}spawn=setInterval(add,420);timer=setInterval(()=>{time--;$('#time').textContent=time;if(time<=0){clearInterval(timer);clearInterval(spawn);saveBest('balloons',score);field.innerHTML=`<div class="bigPrompt" style="color:#14304d;padding-top:100px">🏆 ${score} palloncini!</div>`}},1000);cleanup=()=>{clearInterval(timer);clearInterval(spawn)}}
function memory(){const pool=['🐼','🦁','🐸','🐰','🐵','🐧','🦊','🐶'];const vals=[...pool,...pool].sort(()=>Math.random()-.5);let open=[],done=new Set(),moves=0;area.innerHTML=hud(0,'Mosse')+`<div class="memoryGrid" id="mem"></div><div class="result" id="result"></div>`;vals.forEach((v,i)=>{const b=document.createElement('button');b.className='memCard';b.textContent='?';b.addEventListener('click',()=>{if(open.length===2||open.includes(i)||done.has(i))return;b.textContent=v;open.push(i);if(open.length===2){moves++;$('#score').textContent=moves;const[a,c]=open;if(vals[a]===vals[c]){done.add(a);done.add(c);b.parentNode.children[a].classList.add('done');b.parentNode.children[c].classList.add('done');open=[];if(done.size===vals.length){const rating=Math.max(1,40-moves);saveBest('memory',rating);$('#result').textContent=`🎉 Completato in ${moves} mosse!`}}else setTimeout(()=>{b.parentNode.children[a].textContent='?';b.parentNode.children[c].textContent='?';open=[]},650)}});$('#mem').append(b)})}
function whack(){let score=0,time=20,pos=-1,timer,tick;area.innerHTML=hud()+`<div class="hudPill" style="display:inline-block">Tempo: <b id="time">20</b>s</div><div class="whackGrid" id="holes"></div>`;for(let i=0;i<9;i++){const b=document.createElement('button');b.className='hole';b.textContent='🕳️';b.addEventListener('click',()=>{if(i===pos){score++;$('#score').textContent=score;pos=-1;b.textContent='💥'}});$('#holes').append(b)}function move(){const hs=$$('.hole');hs.forEach(x=>x.textContent='🕳️');pos=Math.floor(Math.random()*9);hs[pos].textContent='🐹'}tick=setInterval(move,650);timer=setInterval(()=>{time--;$('#time').textContent=time;if(time<=0){clearInterval(timer);clearInterval(tick);saveBest('whack',score);$('#holes').innerHTML=`<div class="bigPrompt" style="grid-column:1/4">🏆 ${score} prese!</div>`}},1000);cleanup=()=>{clearInterval(timer);clearInterval(tick)}}
function catchStars(){let score=0,time=25,x=220,keys={},drops=[],raf,last=0,timer;area.innerHTML=hud()+`<div class="hudPill" style="display:inline-block">Tempo: <b id="time">25</b>s</div><div class="catchArea" id="catch"><div class="basket" id="basket"></div></div><div class="gameButtons"><button id="left">⬅️</button><button id="right">➡️</button></div>`;const f=$('#catch'),basket=$('#basket');function clamp(){x=Math.max(0,Math.min(f.clientWidth-72,x));basket.style.left=x+'px'}function addStar(){const s=document.createElement('div');s.className='starDrop';s.textContent='⭐';s.x=Math.random()*(f.clientWidth-35);s.y=-35;s.style.left=s.x+'px';s.style.top=s.y+'px';f.append(s);drops.push(s)}function loop(t){if(t-last>700){addStar();last=t}if(keys.l)x-=4;if(keys.r)x+=4;clamp();drops.forEach(s=>{s.y+=2.7;s.style.top=s.y+'px';if(s.y>280&&s.y<330&&s.x>x-20&&s.x<x+72){score++;$('#score').textContent=score;s.remove();s.dead=true}else if(s.y>340){s.remove();s.dead=true}});drops=drops.filter(s=>!s.dead);raf=requestAnimationFrame(loop)}function press(k,v){keys[k]=v}[['#left','l'],['#right','r']].forEach(([q,k])=>{const b=$(q);b.addEventListener('pointerdown',()=>press(k,true));b.addEventListener('pointerup',()=>press(k,false));b.addEventListener('pointercancel',()=>press(k,false))});clamp();raf=requestAnimationFrame(loop);timer=setInterval(()=>{time--;$('#time').textContent=time;if(time<=0){clearInterval(timer);cancelAnimationFrame(raf);saveBest('catch',score);f.innerHTML=`<div class="bigPrompt" style="padding-top:100px">🏆 ${score} stelle!</div>`}},1000);cleanup=()=>{clearInterval(timer);cancelAnimationFrame(raf)}}
function draw(){area.innerHTML=`<div class="gameButtons" style="margin-bottom:10px"><button data-c="#1c7df2">🔵</button><button data-c="#e7435b">🔴</button><button data-c="#25b765">🟢</button><button data-c="#111111">⚫</button><button id="clearDraw">🗑️ Pulisci</button></div><canvas id="drawC" class="drawCanvas" width="650" height="420"></canvas>`;const c=$('#drawC'),ctx=c.getContext('2d');ctx.lineWidth=9;ctx.lineCap='round';ctx.strokeStyle='#1c7df2';let down=false,last=null;function point(e){const r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]}c.addEventListener('pointerdown',e=>{down=true;last=point(e);c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!down)return;const p=point(e);ctx.beginPath();ctx.moveTo(...last);ctx.lineTo(...p);ctx.stroke();last=p});c.addEventListener('pointerup',()=>down=false);$$('[data-c]').forEach(b=>b.addEventListener('click',()=>ctx.strokeStyle=b.dataset.c));$('#clearDraw').addEventListener('click',()=>ctx.clearRect(0,0,c.width,c.height))}
function math(){let score=0,round=0,answer=0;area.innerHTML=hud()+`<div class="bigPrompt" id="problem"></div><div class="numberGrid" id="answers"></div><div class="result" id="result"></div>`;const next=()=>{if(++round>12){saveBest('math',score);$('#problem').textContent=`🏆 ${score}/12`;$('#answers').innerHTML='';return}let a=Math.floor(Math.random()*11),b=Math.floor(Math.random()*11),minus=Math.random()<.35;if(minus&&b>a)[a,b]=[b,a];answer=minus?a-b:a+b;$('#problem').textContent=`${a} ${minus?'−':'+'} ${b} = ?`;let set=new Set([answer]);while(set.size<3)set.add(Math.max(0,answer+Math.floor(Math.random()*7)-3));$('#answers').innerHTML='';[...set].sort(()=>Math.random()-.5).forEach(v=>{const bt=document.createElement('button');bt.className='numberBtn';bt.textContent=v;bt.addEventListener('click',()=>{if(v===answer){score++;$('#score').textContent=score;$('#result').textContent='✅ Giusto!'}else $('#result').textContent=`Risposta: ${answer}`;setTimeout(()=>{$('#result').textContent='';next()},450)});$('#answers').append(bt)})};next()}
function tris(){let board=Array(9).fill(''),turn='X',ended=false;area.innerHTML=`<div class="gameHud"><span class="hudPill">Tu: X</span><span class="hudPill">Computer: O</span></div><div class="ticGrid" id="tic"></div><div class="result" id="result"></div>`;const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];function check(p){return wins.some(w=>w.every(i=>board[i]===p))}function draw(){const e=board.every(Boolean);if(check('X')){ended=true;$('#result').textContent='🎉 Hai vinto!'}else if(check('O')){ended=true;$('#result').textContent='🤖 Vince il computer'}else if(e){ended=true;$('#result').textContent='🤝 Pareggio!'}}function cpu(){if(ended)return;const empty=board.map((v,i)=>v?null:i).filter(v=>v!==null);if(!empty.length)return;let pick=empty.find(i=>{board[i]='O';const w=check('O');board[i]='';return w});if(pick==null)pick=empty.find(i=>{board[i]='X';const w=check('X');board[i]='';return w});if(pick==null)pick=empty[Math.floor(Math.random()*empty.length)];board[pick]='O';$('#tic').children[pick].textContent='O';draw()}for(let i=0;i<9;i++){const b=document.createElement('button');b.className='ticCell';b.addEventListener('click',()=>{if(ended||board[i])return;board[i]='X';b.textContent='X';draw();if(!ended)setTimeout(cpu,300)});$('#tic').append(b)}}
function maze(){const map=["11111111111","10000010001","10111010101","10100000101","10101111101","10001000001","11101011101","10001010001","10111010101","10000000001","11111111111"].map(r=>r.split(''));let p=[1,1],goal=[9,9],moves=0;area.innerHTML=hud(0,'Mosse')+`<div class="mazeGrid" id="maze" style="grid-template-columns:repeat(11,28px)"></div><div class="dpad"><button class="up">⬆️</button><button class="left">⬅️</button><button class="down">⬇️</button><button class="right">➡️</button></div><div class="result" id="result"></div>`;function drawMaze(){$('#maze').innerHTML='';map.forEach((row,y)=>row.forEach((v,x)=>{const c=document.createElement('div');c.className='mazeCell '+(v==='1'?'wall':'');if(x===p[0]&&y===p[1]){c.classList.add('player');c.textContent='🙂'}if(x===goal[0]&&y===goal[1]){c.classList.add('goal');c.textContent='🏁'}$('#maze').append(c)}))}function move(dx,dy){const nx=p[0]+dx,ny=p[1]+dy;if(map[ny]?.[nx]==='0'){p=[nx,ny];moves++;$('#score').textContent=moves;drawMaze();if(nx===goal[0]&&ny===goal[1]){$('#result').textContent=`🎉 Arrivato in ${moves} mosse!`;saveBest('maze',Math.max(1,100-moves))}}}drawMaze();$$('.dpad button').forEach(b=>b.addEventListener('click',()=>{if(b.classList.contains('up'))move(0,-1);if(b.classList.contains('down'))move(0,1);if(b.classList.contains('left'))move(-1,0);if(b.classList.contains('right'))move(1,0)}))}
function snake(){const W=16,H=16,S=22;let s=[[8,8],[7,8],[6,8]],food=[3,4],dir=[1,0],next=dir,score=0,timer;area.innerHTML=hud()+`<div class="canvasWrap"><canvas class="gameCanvas" id="snakeC" width="${W*S}" height="${H*S}"></canvas></div><div class="dpad"><button class="up">⬆️</button><button class="left">⬅️</button><button class="down">⬇️</button><button class="right">➡️</button></div><div class="result" id="result"></div>`;const c=$('#snakeC'),ctx=c.getContext('2d');function newFood(){do food=[Math.floor(Math.random()*W),Math.floor(Math.random()*H)];while(s.some(p=>p[0]===food[0]&&p[1]===food[1]))}function draw(){ctx.fillStyle='#06131f';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#ff4560';ctx.beginPath();ctx.arc(food[0]*S+S/2,food[1]*S+S/2,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#34dc72';s.forEach(([x,y])=>ctx.fillRect(x*S+2,y*S+2,S-4,S-4))}function set(d){if(d[0]!==-dir[0]||d[1]!==-dir[1])next=d}$$('.dpad button').forEach(b=>b.addEventListener('click',()=>{if(b.classList.contains('up'))set([0,-1]);if(b.classList.contains('down'))set([0,1]);if(b.classList.contains('left'))set([-1,0]);if(b.classList.contains('right'))set([1,0])}));timer=setInterval(()=>{dir=next;const h=[s[0][0]+dir[0],s[0][1]+dir[1]];if(h[0]<0||h[0]>=W||h[1]<0||h[1]>=H||s.some(p=>p[0]===h[0]&&p[1]===h[1])){clearInterval(timer);saveBest('snake',score);$('#result').textContent=`Game over • ${score} punti`;return}s.unshift(h);if(h[0]===food[0]&&h[1]===food[1]){score++;$('#score').textContent=score;newFood()}else s.pop();draw()},150);draw();cleanup=()=>clearInterval(timer)}
function game2048(){let board=Array(16).fill(0),score=0;function add(){const e=board.map((v,i)=>v?null:i).filter(v=>v!==null);if(!e.length)return;board[e[Math.floor(Math.random()*e.length)]]=Math.random()<.9?2:4}add();add();area.innerHTML=hud()+`<div class="tiles2048" id="tiles"></div><div class="dpad"><button class="up">⬆️</button><button class="left">⬅️</button><button class="down">⬇️</button><button class="right">➡️</button></div>`;function render(){const box=$('#tiles');box.innerHTML='';board.forEach(v=>{const d=document.createElement('div');d.className='tile2048';d.textContent=v||'';if(v)d.style.background=`hsl(${45-Math.log2(v)*4} 80% ${Math.max(45,84-Math.log2(v)*5)}%)`;box.append(d)});$('#score').textContent=score;saveBest('2048',score)}function line(vals){let a=vals.filter(Boolean),out=[];for(let i=0;i<a.length;i++){if(a[i]===a[i+1]){out.push(a[i]*2);score+=a[i]*2;i++}else out.push(a[i])}while(out.length<4)out.push(0);return out}function move(dx,dy){const before=board.join();if(dx){for(let y=0;y<4;y++){let row=board.slice(y*4,y*4+4);if(dx>0)row.reverse();row=line(row);if(dx>0)row.reverse();row.forEach((v,x)=>board[y*4+x]=v)}}else{for(let x=0;x<4;x++){let col=[0,1,2,3].map(y=>board[y*4+x]);if(dy>0)col.reverse();col=line(col);if(dy>0)col.reverse();col.forEach((v,y)=>board[y*4+x]=v)}}if(board.join()!==before)add();render()}$$('.dpad button').forEach(b=>b.addEventListener('click',()=>{if(b.classList.contains('up'))move(0,-1);if(b.classList.contains('down'))move(0,1);if(b.classList.contains('left'))move(-1,0);if(b.classList.contains('right'))move(1,0)}));render()}
function brick(){const c=document.createElement('canvas');c.id='brickC';c.className='gameCanvas';c.width=560;c.height=360;area.innerHTML=hud()+`<div class="canvasWrap"></div><div class="gameButtons"><button id="bLeft">⬅️</button><button id="bRight">➡️</button></div><div class="result" id="result"></div>`;$('.canvasWrap').append(c);const x=c.getContext('2d');let px=230,bx=280,by=260,vx=3,vy=-3,keys={l:false,r:false},bricks=[],score=0,raf;for(let r=0;r<4;r++)for(let col=0;col<8;col++)bricks.push({x:17+col*67,y:20+r*30,w:58,h:20,on:true});[['#bLeft','l'],['#bRight','r']].forEach(([q,k])=>{$(q).addEventListener('pointerdown',()=>keys[k]=true);$(q).addEventListener('pointerup',()=>keys[k]=false);$(q).addEventListener('pointercancel',()=>keys[k]=false)});function loop(){if(keys.l)px-=6;if(keys.r)px+=6;px=Math.max(0,Math.min(c.width-100,px));bx+=vx;by+=vy;if(bx<8||bx>c.width-8)vx*=-1;if(by<8)vy*=-1;if(by>325&&by<350&&bx>px&&bx<px+100&&vy>0)vy*=-1;bricks.forEach(b=>{if(b.on&&bx>b.x&&bx<b.x+b.w&&by>b.y&&by<b.y+b.h){b.on=false;vy*=-1;score++;$('#score').textContent=score}});if(by>370){saveBest('brick',score);$('#result').textContent='Game over!';return}if(bricks.every(b=>!b.on)){saveBest('brick',score);$('#result').textContent='🎉 Hai rotto tutti i mattoni!';return}x.fillStyle='#071523';x.fillRect(0,0,c.width,c.height);x.fillStyle='#45a9ff';bricks.forEach(b=>b.on&&x.fillRect(b.x,b.y,b.w,b.h));x.fillStyle='#fff';x.fillRect(px,340,100,10);x.beginPath();x.arc(bx,by,7,0,Math.PI*2);x.fill();raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);cleanup=()=>cancelAnimationFrame(raf)}
function race(){const c=document.createElement('canvas');c.className='gameCanvas';c.width=360;c.height=500;area.innerHTML=hud()+`<div class="canvasWrap"></div><div class="gameButtons"><button id="rLeft">⬅️</button><button id="rRight">➡️</button></div><div class="result" id="result"></div>`;$('.canvasWrap').append(c);const x=c.getContext('2d'),lanes=[80,180,280];let lane=1,obs=[],score=0,frame=0,raf,ended=false;function move(d){lane=Math.max(0,Math.min(2,lane+d))}$('#rLeft').addEventListener('click',()=>move(-1));$('#rRight').addEventListener('click',()=>move(1));function loop(){if(ended)return;frame++;if(frame%55===0)obs.push({lane:Math.floor(Math.random()*3),y:-70});obs.forEach(o=>o.y+=4.2);obs=obs.filter(o=>o.y<560);if(obs.some(o=>o.lane===lane&&o.y>390&&o.y<475)){ended=true;saveBest('race',score);$('#result').textContent=`💥 Gara finita • ${score} punti`;return}if(frame%30===0){score++;$('#score').textContent=score}x.fillStyle='#1c2632';x.fillRect(0,0,360,500);x.strokeStyle='#fff8';x.setLineDash([24,18]);x.lineWidth=4;[130,230].forEach(xx=>{x.beginPath();x.moveTo(xx,0);x.lineTo(xx,500);x.stroke()});x.setLineDash([]);x.font='52px sans-serif';x.textAlign='center';x.fillText('🏎️',lanes[lane],455);obs.forEach(o=>x.fillText('🚙',lanes[o.lane],o.y));raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);cleanup=()=>cancelAnimationFrame(raf)}
function quiz(){const qs=[['Quale animale fa “miao”?',['🐱 Gatto','🐶 Cane','🐮 Mucca'],0],['Quanto fa 5 + 3?',['7','8','9'],1],['Quale vive nel mare?',['🐘 Elefante','🐬 Delfino','🐰 Coniglio'],1],['Quanti giorni ha una settimana?',['5','7','10'],1],['Quale è un frutto?',['🍎 Mela','🥕 Carota','🥦 Broccolo'],0],['Quale pianeta abitiamo?',['Marte','Terra','Giove'],1],['Quale numero viene dopo 19?',['18','20','21'],1],['Quale mezzo vola?',['✈️ Aereo','🚲 Bici','🚂 Treno'],0],['Il ghiaccio è…',['Caldo','Freddo','Morbido'],1],['Quale è più grande?',['🐭 Topo','🐘 Elefante','🐜 Formica'],1]];let k=0,score=0;area.innerHTML=hud()+`<div class="bigPrompt" id="q"></div><div class="gameButtons" id="answers"></div><div class="result" id="result"></div>`;function next(){if(k>=qs.length){saveBest('quiz',score);$('#q').textContent=`🏆 ${score}/${qs.length}`;$('#answers').innerHTML='';return}const q=qs[k];$('#q').textContent=q[0];$('#answers').innerHTML='';q[1].forEach((v,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=v;b.addEventListener('click',()=>{if(i===q[2]){score++;$('#score').textContent=score;$('#result').textContent='✅ Esatto!'}else $('#result').textContent=`Risposta: ${q[1][q[2]]}`;k++;setTimeout(()=>{$('#result').textContent='';next()},500)});$('#answers').append(b)})}next()}

function moto(){
  let score=0,coins=0,lane=1,frame=0,objects=[],raf,ended=false,speed=4.5;const lanes=[16.7,50,83.3];
  area.innerHTML=hud()+`<div class="gameHud"><span class="hudPill">Monete: <b id="coins">0</b> 🪙</span><span class="hudPill">Velocità: <b id="speed">1</b></span></div><div class="trackStage" id="motoTrack"><div class="roadObj bike" id="bike">🏍️</div></div><div class="gameButtons"><button id="mLeft">⬅️ Sinistra</button><button id="mRight">Destra ➡️</button></div><div class="result" id="result"></div>`;
  const track=$('#motoTrack'),bike=$('#bike');bike.style.left=lanes[lane]+'%';bike.style.top='84%';voice('Moto Sprint. Schiva le auto e prendi le monete!');
  function move(d){if(ended)return;lane=Math.max(0,Math.min(2,lane+d));bike.style.left=lanes[lane]+'%';sfx('tap')}
  $('#mLeft').addEventListener('click',()=>move(-1));$('#mRight').addEventListener('click',()=>move(1));
  function spawn(){const coin=Math.random()<.38,o=document.createElement('div');o.className='roadObj';o.textContent=coin?'🪙':(Math.random()<.5?'🚗':'🚙');o.dataset.kind=coin?'coin':'car';o.dataset.lane=Math.floor(Math.random()*3);o.y=-10;o.style.left=lanes[o.dataset.lane]+'%';o.style.top=o.y+'%';o.style.fontSize=coin?'34px':'48px';track.append(o);objects.push(o)}
  function loop(){if(ended)return;frame++;if(frame%Math.max(34,62-Math.floor(score/12))===0)spawn();speed=Math.min(8.3,4.5+score*.015);objects.forEach(o=>{o.y+=speed*.15;o.style.top=o.y+'%';if(!o.dead&&+o.dataset.lane===lane&&o.y>76&&o.y<92){if(o.dataset.kind==='coin'){coins++;score+=4;$('#coins').textContent=coins;$('#score').textContent=score;sfx('coin');o.dead=true;o.remove()}else{ended=true;sfx('bad');voice(`Gara finita. Hai fatto ${score} punti`);saveBest('moto',score);$('#result').textContent=`💥 Gara finita • ${score} punti • ${coins} monete`;}}if(o.y>108){if(o.dataset.kind==='car'){score++;$('#score').textContent=score}o.dead=true;o.remove()}});objects=objects.filter(o=>!o.dead);$('#speed').textContent=(1+Math.floor((speed-4.5)/1.1));if(!ended)raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);cleanup=()=>{ended=true;cancelAnimationFrame(raf);objects.forEach(o=>o.remove())}
}

function coloring(){
  const templates=['🐱 Gatto','🐶 Cane','🐟 Pesce','🦋 Farfalla','🐢 Tartaruga','🦁 Leone','🦖 Dinosauro','🌸 Fiore','🌳 Albero','🌻 Girasole','🏡 Casa','☀️ Sole'];let current=0,color='#ff4f8b',drawing=false,last=null;
  area.innerHTML=`<div class="bigPrompt">🎨 Colora come vuoi!</div><div class="templateRow" id="templates"></div><div class="palette" id="palette"></div><canvas id="colorC" class="colorCanvas" width="760" height="500"></canvas><div class="gameButtons" style="margin-top:12px"><button id="erase">🧽 Gomma</button><button id="clearColor">🗑️ Ricomincia</button></div><p class="soundNote">Scegli un disegno, un colore e passa il dito sul foglio.</p>`;
  const c=$('#colorC'),x=c.getContext('2d');const colors=['#ff4f8b','#ff3939','#ff962f','#ffd835','#54d76a','#28b7ff','#496cff','#9d5cff','#6b4328','#111111','#ffffff'];
  function base(){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#27374d';x.fillStyle='#fff';x.lineWidth=8;x.lineCap='round';x.lineJoin='round';const cx=380,cy=250;function circle(a,b,r){x.beginPath();x.arc(a,b,r,0,Math.PI*2);x.stroke()}function oval(a,b,rx,ry){x.beginPath();x.ellipse(a,b,rx,ry,0,0,Math.PI*2);x.stroke()}const t=current;
    if(t===0||t===1||t===5){circle(cx,230,120);circle(335,215,10);circle(425,215,10);x.beginPath();x.moveTo(340,285);x.quadraticCurveTo(380,315,420,285);x.stroke();x.beginPath();x.moveTo(290,145);x.lineTo(315,75);x.lineTo(350,135);x.stroke();x.beginPath();x.moveTo(410,135);x.lineTo(445,75);x.lineTo(470,145);x.stroke();if(t===5){x.lineWidth=20;for(let i=0;i<12;i++){const a=i*Math.PI/6;x.beginPath();x.moveTo(cx+Math.cos(a)*125,230+Math.sin(a)*125);x.lineTo(cx+Math.cos(a)*160,230+Math.sin(a)*160);x.stroke()}x.lineWidth=8}}
    else if(t===2){oval(cx,250,170,95);x.beginPath();x.moveTo(550,250);x.lineTo(650,165);x.lineTo(650,335);x.closePath();x.stroke();circle(310,225,9)}
    else if(t===3){oval(305,220,100,85);oval(455,220,100,85);oval(315,335,90,75);oval(445,335,90,75);x.beginPath();x.moveTo(380,130);x.lineTo(380,390);x.stroke()}
    else if(t===4){oval(cx,260,150,105);circle(cx,260,85);circle(535,260,48);[['260','180'],['260','340'],['485','155'],['485','365']].forEach(v=>circle(+v[0],+v[1],35))}
    else if(t===6){oval(350,250,165,95);circle(525,190,70);x.beginPath();x.moveTo(205,245);x.lineTo(135,190);x.lineTo(150,295);x.closePath();x.stroke();for(let i=0;i<6;i++){x.beginPath();x.moveTo(270+i*35,165);x.lineTo(290+i*35,110);x.lineTo(315+i*35,165);x.stroke()}}
    else if(t===7||t===9){circle(cx,210,75);for(let i=0;i<12;i++){const a=i*Math.PI/6;circle(cx+Math.cos(a)*110,210+Math.sin(a)*110,38)}x.beginPath();x.moveTo(cx,285);x.lineTo(cx,450);x.stroke();x.beginPath();x.moveTo(cx,350);x.quadraticCurveTo(300,320,285,380);x.quadraticCurveTo(350,390,cx,350);x.stroke()}
    else if(t===8){x.beginPath();x.moveTo(350,430);x.lineTo(350,260);x.lineTo(410,260);x.lineTo(410,430);x.stroke();circle(380,175,145)}
    else if(t===10){x.strokeRect(230,230,300,220);x.beginPath();x.moveTo(200,230);x.lineTo(380,80);x.lineTo(560,230);x.stroke();x.strokeRect(350,330,70,120);x.strokeRect(270,280,70,70);x.strokeRect(450,280,55,70)}
    else{circle(cx,230,115);for(let i=0;i<12;i++){const a=i*Math.PI/6;x.beginPath();x.moveTo(cx+Math.cos(a)*145,230+Math.sin(a)*145);x.lineTo(cx+Math.cos(a)*190,230+Math.sin(a)*190);x.stroke()}}
  }
  templates.forEach((t,i)=>{const b=document.createElement('button');b.className='templateBtn';b.textContent=t;b.addEventListener('click',()=>{current=i;base();voice(t.split(' ')[1]||t)});$('#templates').append(b)});
  colors.forEach(col=>{const b=document.createElement('button');b.className='paintColor';b.style.background=col;b.addEventListener('click',()=>{color=col;$$('.paintColor').forEach(q=>q.classList.remove('active'));b.classList.add('active');sfx('tap')});$('#palette').append(b)});$('.paintColor').classList.add('active');
  function pos(e){const r=c.getBoundingClientRect(),p=e.touches?.[0]||e;return[(p.clientX-r.left)*c.width/r.width,(p.clientY-r.top)*c.height/r.height]}
  function down(e){drawing=true;last=pos(e);e.preventDefault()}function move(e){if(!drawing)return;const p=pos(e);x.strokeStyle=color;x.lineWidth=color==='#ffffff'?34:22;x.lineCap='round';x.beginPath();x.moveTo(...last);x.lineTo(...p);x.stroke();last=p;e.preventDefault()}function up(){drawing=false;last=null}
  c.addEventListener('pointerdown',down);c.addEventListener('pointermove',move);window.addEventListener('pointerup',up);$('#erase').addEventListener('click',()=>color='#ffffff');$('#clearColor').addEventListener('click',base);base();voice('Scegli un disegno e coloralo con il dito');cleanup=()=>window.removeEventListener('pointerup',up)
}

function piano(){const notes=[261.63,293.66,329.63,349.23,392,440,493.88,523.25],names=['DO','RE','MI','FA','SOL','LA','SI','DO'];area.innerHTML=`<div class="bigPrompt">🎹 Piano magico</div><div class="piano" id="piano"></div><div class="result" id="result">Tocca i tasti. Ogni nota ha un suono vero.</div>`;notes.forEach((n,i)=>{const b=document.createElement('button');b.className='pianoKey';b.textContent=names[i];b.addEventListener('pointerdown',()=>{tone(n,.45,'sine',.09);b.classList.add('on');voice(names[i])});b.addEventListener('pointerup',()=>b.classList.remove('on'));b.addEventListener('pointercancel',()=>b.classList.remove('on'));$('#piano').append(b)});voice('Piano magico. Suona la tua melodia')}
function drums(){const pads=[['🥁','Cassa',90,'sine'],['🪘','Rullante',180,'square'],['🥁','Tom',130,'triangle'],['✨','Piatto',900,'sawtooth'],['👏','Clap',420,'square'],['🔔','Campana',720,'sine']];area.innerHTML=`<div class="bigPrompt">🥁 Batteria Kids</div><div class="drumGrid" id="drums"></div><div class="result">Crea il tuo ritmo!</div>`;pads.forEach(([em,n,f,t],i)=>{const b=document.createElement('button');b.className='drumPad';b.style.setProperty('--pad',`hsl(${i*55+10} 62% 48%)`);b.innerHTML=`${em}<small style="display:block;font-size:13px">${n}</small>`;b.addEventListener('pointerdown',()=>{tone(f,.16,t,.09);if(n==='Piatto')tone(f*1.5,.22,'square',.025)});$('#drums').append(b)});voice('Batteria Kids. Crea il tuo ritmo')}
function simon(){const cols=[['#ef5350',261.63],['#42a5f5',329.63],['#66bb6a',392],['#ffca28',523.25]];let seq=[],turn=0,locked=true,score=0,timers=[];area.innerHTML=hud()+`<div class="bigPrompt">🧠 Ripeti la sequenza</div><div class="simonGrid" id="simon"></div><div class="result" id="result">Premi Inizia</div><button id="simonStart">▶ Inizia</button>`;cols.forEach(([c,f],i)=>{const b=document.createElement('button');b.className='simonPad';b.style.background=c;b.addEventListener('click',()=>tap(i));$('#simon').append(b)});function flash(i,d=450){const b=$$('.simonPad')[i];b.classList.add('flash');tone(cols[i][1],.25,'sine',.07);timers.push(setTimeout(()=>b.classList.remove('flash'),d*.65))}function show(){locked=true;turn=0;seq.push(Math.floor(Math.random()*4));$('#result').textContent='Guarda e ascolta…';seq.forEach((v,i)=>timers.push(setTimeout(()=>flash(v),500+i*650)));timers.push(setTimeout(()=>{locked=false;$('#result').textContent='Adesso tocca tu!'},500+seq.length*650))}function tap(i){if(locked)return;flash(i,220);if(i!==seq[turn]){sfx('bad');locked=true;saveBest('simon',score);$('#result').textContent=`Ops! Record: ${Math.max(best('simon'),score)}`;voice('Ops, riprova');return}turn++;if(turn===seq.length){score++;$('#score').textContent=score;sfx('good');locked=true;timers.push(setTimeout(show,700))}}$('#simonStart').addEventListener('click',()=>{seq=[];score=0;$('#score').textContent=0;show()});cleanup=()=>timers.forEach(clearTimeout)}
function alphabet(){const L='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');const words={A:'Albero',B:'Balena',C:'Casa',D:'Delfino',E:'Elefante',F:'Fiore',G:'Gatto',H:'Hotel',I:'Isola',J:'Jeans',K:'Kiwi',L:'Leone',M:'Mela',N:'Nave',O:'Orso',P:'Palla',Q:'Quadro',R:'Rana',S:'Sole',T:'Tigre',U:'Uva',V:'Volpe',W:'Web',X:'Xilofono',Y:'Yogurt',Z:'Zebra'};area.innerHTML=`<div class="letterHero" id="letterHero">A</div><div class="bigPrompt" id="letterWord">A come Albero</div><div class="gameButtons" id="letters"></div>`;L.forEach(l=>{const b=document.createElement('button');b.className='choice';b.textContent=l;b.addEventListener('click',()=>{$('#letterHero').textContent=l;$('#letterWord').textContent=`${l} come ${words[l]}`;voice(`${l}. ${l} come ${words[l]}`);tone(300+(l.charCodeAt(0)-65)*13,.08)});$('#letters').append(b)});voice('Tocca una lettera e ascolta')}
function words(){const qs=[['GATTO','🐱'],['SOLE','☀️'],['MELA','🍎'],['CANE','🐶'],['PESCE','🐟'],['LUNA','🌙'],['CASA','🏠'],['FIORE','🌸']];let q=0,score=0,answer='';area.innerHTML=hud()+`<div class="bigPrompt" id="pic"></div><div class="wordSlots" id="slots"></div><div class="gameButtons" id="letters"></div><div class="result" id="result"></div>`;function next(){if(q>=qs.length){saveBest('words',score);$('#pic').textContent=`🏆 ${score}/${qs.length}`;$('#letters').innerHTML='';return}const [w,em]=qs[q];answer='';$('#pic').textContent=em;$('#slots').innerHTML=w.split('').map(()=>'<div class="wordSlot"></div>').join('');const mix=w.split('').sort(()=>Math.random()-.5);$('#letters').innerHTML='';mix.forEach(ch=>{const b=document.createElement('button');b.className='choice';b.textContent=ch;b.addEventListener('click',()=>{if(answer.length>=w.length)return;answer+=ch;$('#slots').children[answer.length-1].textContent=ch;b.disabled=true;if(answer.length===w.length){if(answer===w){score++;$('#score').textContent=score;sfx('good');voice('Bravissimo')}else{sfx('bad');voice(`La parola era ${w}`)}q++;setTimeout(next,650)}});$('#letters').append(b)});voice(`Costruisci la parola ${w}`)}next()}
function fishing(){let score=0,time=30,hookX=50,hookY=15,down=false,items=[],raf,timer,frame=0;area.innerHTML=hud()+`<div class="hudPill">Tempo: <b id="time">30</b>s</div><div class="kidStage" id="sea" style="background:linear-gradient(#8ee3ff 0 25%,#1688d4 25% 100%)"><div id="hook" style="position:absolute;font-size:46px;left:50%;top:8%;transform:translate(-50%,-50%)">🎣</div></div><div class="gameButtons"><button id="fishL">⬅️</button><button id="fishDrop">⬇️ Pesca</button><button id="fishR">➡️</button></div>`;const sea=$('#sea'),hook=$('#hook');function spawn(){const o=document.createElement('div');o.className='roadObj';o.textContent=Math.random()<.15?'🥾':['🐟','🐠','🐡'][Math.floor(Math.random()*3)];o.bad=o.textContent==='🥾';o.x=10+Math.random()*80;o.y=40+Math.random()*50;o.v=(Math.random()<.5?-1:1)*(0.08+Math.random()*.12);o.style.left=o.x+'%';o.style.top=o.y+'%';o.style.fontSize='38px';sea.append(o);items.push(o)}for(let i=0;i<8;i++)spawn();function loop(){frame++;items.forEach(o=>{o.x+=o.v;if(o.x<5||o.x>95)o.v*=-1;o.style.left=o.x+'%'});if(down)hookY=Math.min(88,hookY+1.2);else hookY=Math.max(15,hookY-1.4);hook.style.left=hookX+'%';hook.style.top=hookY+'%';if(down){const hit=items.find(o=>Math.abs(o.x-hookX)<7&&Math.abs(o.y-hookY)<8);if(hit){if(hit.bad){score=Math.max(0,score-2);sfx('bad')}else{score+=2;sfx('coin')}$('#score').textContent=score;hit.remove();items=items.filter(x=>x!==hit);spawn();down=false}}raf=requestAnimationFrame(loop)}$('#fishL').addEventListener('click',()=>hookX=Math.max(8,hookX-10));$('#fishR').addEventListener('click',()=>hookX=Math.min(92,hookX+10));$('#fishDrop').addEventListener('click',()=>{down=true;sfx('jump')});timer=setInterval(()=>{time--;$('#time').textContent=time;if(time<=0){clearInterval(timer);cancelAnimationFrame(raf);saveBest('fishing',score);voice(`Tempo finito. ${score} punti`)}},1000);raf=requestAnimationFrame(loop);cleanup=()=>{clearInterval(timer);cancelAnimationFrame(raf)}}
function dino(){runnerGame('dino','🦖','🌵','🥚','Dino Jump')}
function nihal(){runnerGame('nihal','🦕','🌴','⭐','Forza Nihal! Dino Adventure',true)}
function runnerGame(id,hero,obstacle,collect,titleText,personal=false){let y=0,vy=0,score=0,frame=0,obs=[],items=[],raf,ended=false;area.innerHTML=hud()+`<div class="nameBanner">${titleText}</div><div class="kidStage" id="runStage"><div id="runner" style="position:absolute;left:14%;bottom:15%;font-size:64px">${hero}</div></div><button id="jumpBtn">⬆️ SALTA</button><div class="result" id="result"></div>`;const st=$('#runStage'),r=$('#runner');function jump(){if(y<=0.5){vy=12;sfx('jump')}}$('#jumpBtn').addEventListener('click',jump);st.addEventListener('pointerdown',jump);if(personal)voice('Forza Nihal! Corri con il dinosauro e prendi le stelle!');function spawn(kind){const o=document.createElement('div');o.className='roadObj';o.textContent=kind==='ob'?obstacle:collect;o.kind=kind;o.x=108;o.style.left=o.x+'%';o.style.top=kind==='ob'?'76%':'55%';o.style.fontSize=kind==='ob'?'50px':'34px';st.append(o);(kind==='ob'?obs:items).push(o)}function loop(){if(ended)return;frame++;if(frame%90===0)spawn('ob');if(frame%120===60)spawn('item');vy-=.65;y+=vy;if(y<0){y=0;vy=0}r.style.transform=`translateY(${-y}px)`;[...obs,...items].forEach(o=>{o.x-=.65;o.style.left=o.x+'%';if(o.x<0){o.dead=true;o.remove()}});const airborne=y>42;obs.forEach(o=>{if(!o.dead&&o.x>9&&o.x<23&&!airborne){ended=true;sfx('bad');saveBest(id,score);$('#result').textContent=`Game over • ${score}`;voice(personal?`Bravo Nihal. Hai fatto ${score} punti`:`Hai fatto ${score} punti`)}});items.forEach(o=>{if(!o.dead&&o.x>9&&o.x<23&&y>15){score+=3;$('#score').textContent=score;sfx('coin');o.dead=true;o.remove()}});obs=obs.filter(o=>!o.dead);items=items.filter(o=>!o.dead);if(frame%40===0){score++;$('#score').textContent=score}if(!ended)raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);cleanup=()=>{ended=true;cancelAnimationFrame(raf)}}
function space(){let x=50,score=0,frame=0,objs=[],raf,ended=false;area.innerHTML=hud()+`<div class="kidStage night" id="spaceStage"><div id="rocket" style="position:absolute;left:50%;bottom:8%;font-size:58px;transform:translateX(-50%)">🚀</div></div><div class="gameButtons"><button id="spL">⬅️</button><button id="spR">➡️</button></div><div class="result" id="result"></div>`;const st=$('#spaceStage'),r=$('#rocket');function spawn(){const o=document.createElement('div');o.className='roadObj';o.good=Math.random()<.3;o.textContent=o.good?'⭐':'☄️';o.x=8+Math.random()*84;o.y=-5;o.style.left=o.x+'%';o.style.top=o.y+'%';o.style.fontSize=o.good?'32px':'45px';st.append(o);objs.push(o)}function move(d){x=Math.max(8,Math.min(92,x+d*12));r.style.left=x+'%'}$('#spL').onclick=()=>move(-1);$('#spR').onclick=()=>move(1);function loop(){if(ended)return;frame++;if(frame%48===0)spawn();objs.forEach(o=>{o.y+=.65;o.style.top=o.y+'%';if(!o.dead&&o.y>79&&o.y<94&&Math.abs(o.x-x)<10){if(o.good){score+=3;sfx('coin');o.dead=true;o.remove()}else{ended=true;sfx('bad');saveBest('space',score);$('#result').textContent=`💥 Missione finita • ${score} punti`}}if(o.y>110){o.dead=true;o.remove()}});objs=objs.filter(o=>!o.dead);if(frame%50===0){score++;$('#score').textContent=score}if(!ended)raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);cleanup=()=>{ended=true;cancelAnimationFrame(raf)}}
function basket(){let score=0,shots=0,power=20,dir=1;area.innerHTML=hud()+`<div class="bigPrompt">🏀 Basket Shot</div><div style="font-size:100px">⛹️‍♂️　　🏀➡️　　🗑️</div><div style="width:min(600px,90%);height:30px;border-radius:99px;background:var(--panel2);overflow:hidden;margin:25px auto"><div id="powerBar" style="height:100%;width:20%;background:linear-gradient(90deg,#45d76a,#ffd23d,#ff4d5a)"></div></div><button id="shoot">🏀 TIRA!</button><div class="result" id="result">Ferma la barra vicino al centro verde.</div>`;let t=setInterval(()=>{power+=dir*2;if(power>=100||power<=5)dir*=-1;$('#powerBar').style.width=power+'%'},35);$('#shoot').onclick=()=>{shots++;const diff=Math.abs(power-58);const hit=diff<17;if(hit){score++;$('#score').textContent=score;sfx('goal');$('#result').textContent='🏀 CANESTRO!';voice('Canestro!')}else{sfx('bad');$('#result').textContent='Quasi! Riprova.'}if(shots>=12){clearInterval(t);saveBest('basket',score);$('#result').textContent=`🏆 ${score} canestri su 12`}};cleanup=()=>clearInterval(t)}
function penalty(){let score=0,shots=0;area.innerHTML=hud()+`<div class="bigPrompt">⚽ Calci di rigore</div><div style="font-size:90px">🥅</div><div class="gameButtons" id="corners"><button data-i="0">↖️</button><button data-i="1">⬆️</button><button data-i="2">↗️</button><button data-i="3">↙️</button><button data-i="4">⬇️</button><button data-i="5">↘️</button></div><div class="result" id="result">Scegli dove tirare.</div>`;$$('#corners button').forEach(b=>b.onclick=()=>{if(shots>=10)return;shots++;const shot=+b.dataset.i,keeper=Math.floor(Math.random()*6);if(shot!==keeper){score++;$('#score').textContent=score;sfx('goal');$('#result').textContent=`⚽ GOOOL! Il portiere è andato ${['↖️','⬆️','↗️','↙️','⬇️','↘️'][keeper]}`;voice('Goal!')}else{sfx('bad');$('#result').textContent='🧤 Parata!'}if(shots===10){saveBest('penalty',score);setTimeout(()=>$('#result').textContent=`🏆 ${score} goal su 10`,400)}})}
function puzzle(){const animals=[['🐼','Panda'],['🦁','Leone'],['🐘','Elefante'],['🐯','Tigre'],['🦄','Unicorno']];let current=0,moves=0;area.innerHTML=hud(0,'Mosse')+`<div class="templateRow" id="puzAnimals"></div><div id="puzBoard" style="display:grid;grid-template-columns:repeat(3,100px);gap:7px;justify-content:center;margin:15px"></div><div class="result" id="result"></div>`;animals.forEach((a,i)=>{const b=document.createElement('button');b.textContent=`${a[0]} ${a[1]}`;b.onclick=()=>{current=i;setup()};$('#puzAnimals').append(b)});let arr=[];function setup(){moves=0;$('#score').textContent=0;arr=[0,1,2,3,4,5,6,7,8].sort(()=>Math.random()-.5);draw()}function draw(){const box=$('#puzBoard');box.innerHTML='';arr.forEach((v,i)=>{const b=document.createElement('button');b.style.cssText='width:100px;height:100px;font-size:52px;padding:0';b.textContent=v===4?animals[current][0]:['🌿','☁️','⭐','🌸','', '🌼','🍃','☀️','🌈'][v];b.onclick=()=>{if(i===0)return;[arr[i-1],arr[i]]=[arr[i],arr[i-1]];moves++;$('#score').textContent=moves;draw();if(arr.every((v,i)=>v===i)){sfx('good');voice('Puzzle completato');saveBest('puzzle',Math.max(1,100-moves));$('#result').textContent='🎉 Puzzle completato!'}};box.append(b)})}setup()}
function bubbles(){let score=0,time=30,target=1,timer,spawn;area.innerHTML=hud()+`<div class="bigPrompt" id="bubblePrompt"></div><div class="hudPill">Tempo: <b id="time">30</b>s</div><div class="bubbleField" id="bubbleField"></div>`;const f=$('#bubbleField');function choose(){target=1+Math.floor(Math.random()*10);$('#bubblePrompt').textContent=`Scoppia il numero ${target}`;voice(`Trova il numero ${target}`)}function add(){const n=1+Math.floor(Math.random()*10),b=document.createElement('button');b.className='bubble';const size=55+Math.random()*30;b.style.width=b.style.height=size+'px';b.style.left=Math.random()*82+'%';b.style.top=Math.random()*75+'%';b.style.background=`hsl(${Math.random()*360} 75% 55%)`;b.textContent=n;b.onclick=()=>{if(n===target){score++;$('#score').textContent=score;sfx('pop');choose()}else sfx('bad');b.remove()};f.append(b);setTimeout(()=>b.remove(),3500)}choose();spawn=setInterval(add,420);timer=setInterval(()=>{time--;$('#time').textContent=time;if(time<=0){clearInterval(timer);clearInterval(spawn);saveBest('bubbles',score);voice(`Bravissimo. ${score} punti`)}},1000);cleanup=()=>{clearInterval(timer);clearInterval(spawn)}}
function niha(){let score=0,time=35,raf,timer,drops=[],x=50,last=0;area.innerHTML=hud()+`<div class="nameBanner">🌈 Niha Rainbow Stars 🌈</div><div class="kidStage" id="nihaStage" style="background:linear-gradient(#8edcff 0 62%,#7dde79 62%)"><div id="nihaBasket" style="position:absolute;bottom:8%;left:50%;font-size:62px;transform:translateX(-50%)">🦄</div></div><div class="gameButtons"><button id="nL">⬅️</button><button id="nR">➡️</button></div><div class="hudPill">Tempo: <b id="time">35</b>s</div>`;const st=$('#nihaStage'),b=$('#nihaBasket');voice('Niha, questa avventura è per te. Prendi tutte le stelle colorate!');function move(d){x=Math.max(8,Math.min(92,x+d*12));b.style.left=x+'%'}$('#nL').onclick=()=>move(-1);$('#nR').onclick=()=>move(1);function loop(t){if(t-last>520){const o=document.createElement('div');o.className='roadObj';o.textContent=['⭐','💖','🌟','🌈'][Math.floor(Math.random()*4)];o.x=5+Math.random()*90;o.y=-5;o.style.left=o.x+'%';o.style.top=o.y+'%';o.style.fontSize='36px';st.append(o);drops.push(o);last=t}drops.forEach(o=>{o.y+=.58;o.style.top=o.y+'%';if(!o.dead&&o.y>77&&o.y<94&&Math.abs(o.x-x)<11){score+=2;$('#score').textContent=score;sfx('coin');o.dead=true;o.remove()}if(o.y>106){o.dead=true;o.remove()}});drops=drops.filter(o=>!o.dead);raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);timer=setInterval(()=>{time--;$('#time').textContent=time;if(time<=0){clearInterval(timer);cancelAnimationFrame(raf);saveBest('niha',score);sfx('goal');voice(`Bravissima Niha. Hai raccolto ${score} punti`) }},1000);cleanup=()=>{clearInterval(timer);cancelAnimationFrame(raf)}}
function imad(){let score=0,time=30,timer,spawn;area.innerHTML=hud()+`<div class="nameBanner">🎈 Imad Balloon Party 🎈</div><div class="bubbleField" id="imadField"></div><div class="hudPill">Tempo: <b id="time">30</b>s</div>`;const f=$('#imadField');voice('Imad, questa festa è per te. Scoppia più palloncini che puoi!');function add(){const b=document.createElement('button');b.className='bubble';const size=58+Math.random()*42;b.style.width=b.style.height=size+'px';b.style.left=Math.random()*80+'%';b.style.top=Math.random()*75+'%';b.style.background=`hsl(${Math.random()*360} 78% 58%)`;b.textContent=['🎈','⭐','🎉','🫧'][Math.floor(Math.random()*4)];b.onclick=()=>{score++;$('#score').textContent=score;sfx('pop');b.remove()};f.append(b);setTimeout(()=>b.remove(),2400)}spawn=setInterval(add,300);timer=setInterval(()=>{time--;$('#time').textContent=time;if(time<=0){clearInterval(timer);clearInterval(spawn);saveBest('imad',score);sfx('goal');voice(`Bravissimo Imad. Hai fatto ${score} punti`) }},1000);cleanup=()=>{clearInterval(timer);clearInterval(spawn)}}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true});
const installDlg=$('#installDialog');$('#howInstall').addEventListener('click',()=>installDlg.showModal());$('.closeInfo').addEventListener('click',()=>installDlg.close());installDlg.addEventListener('cancel',()=>installDlg.close());
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
