const games=[['Snake','🐍','Il classico senza tempo'],['2048','🔢','Unisci i numeri e raggiungi 2048'],['Memory','🧠','Allena la tua memoria'],['Tris','❌','Sfida un amico'],['Brick Breaker','🧱','Rompi tutti i mattoni'],['Car Race','🏎️','Evita gli ostacoli'],['Quiz','❓','Quanto ne sai davvero?'],['BeparyTech Fix','🛠️','Ripara, combina, vinci!']];
const cards=document.querySelector('#cards'),dlg=document.querySelector('#gameDialog'),area=document.querySelector('#gameArea'),title=document.querySelector('#gameTitle');games.forEach(([n,i,d])=>{let c=document.createElement('article');c.className='card';c.innerHTML=`<div class=icon>${i}</div><h3>${n}</h3><p>${d}</p><button>▶ Gioca</button>`;c.querySelector('button').onclick=()=>openGame(n);cards.append(c)});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.go)?.scrollIntoView({behavior:'smooth'}));document.querySelector('#theme').onclick=()=>document.body.classList.toggle('light');document.querySelector('#close').onclick=()=>{stopSnake();dlg.close()};
function openGame(n){stopSnake();title.textContent=n;area.innerHTML='';if(n==='Tris')tris();else if(n==='Memory')memory();else if(n==='Snake')snake();else if(n==='2048')g2048();else if(n==='Quiz')quiz();else mini(n);dlg.showModal()}
function tris(){let s=Array(9).fill(''),p='X';let b=document.createElement('div');b.className='board';s.forEach((_,i)=>{let x=document.createElement('button');x.className='cell';x.onclick=()=>{if(s[i])return;s[i]=p;x.textContent=p;if([[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(a=>a.every(j=>s[j]===p))){setTimeout(()=>alert(p+' ha vinto!'),50)}p=p==='X'?'O':'X'};b.append(x)});area.append(b)}
function memory(){let vals=['📱','🔧','🎮','⚡','📱','🔧','🎮','⚡'].sort(()=>Math.random()-.5),open=[],done=new Set();let b=document.createElement('div');b.className='memory';vals.forEach((v,i)=>{let x=document.createElement('button');x.className='mem';x.textContent='?';x.onclick=()=>{if(done.has(i)||open.includes(i)||open.length===2)return;x.textContent=v;open.push(i);if(open.length===2)setTimeout(()=>{let[a,c]=open;if(vals[a]===vals[c]){done.add(a);done.add(c)}else{b.children[a].textContent='?';b.children[c].textContent='?'}open=[]},600)};b.append(x)});area.append(b)}
let snakeTimer=null;function stopSnake(){if(snakeTimer)clearInterval(snakeTimer);snakeTimer=null}function snake(){let cells=144,s=[65,64,63],f=30,dir=1,box=document.createElement('div');box.className='snakebox';for(let i=0;i<cells;i++)box.append(document.createElement('i'));let draw=()=>{[...box.children].forEach(x=>x.className='');s.forEach(i=>box.children[i]&&(box.children[i].className='s'));box.children[f].className='f'};let set=d=>dir=d;let ctl=document.createElement('div');ctl.className='controls';[['↑','up',-12],['←','left',-1],['↓','down',12],['→','right',1]].forEach(([t,c,d])=>{let b=document.createElement('button');b.textContent=t;b.className=c;b.onclick=()=>set(d);ctl.append(b)});area.append(box,ctl);draw();snakeTimer=setInterval(()=>{let h=s[0]+dir;if(h<0||h>=144||(dir===1&&h%12===0)||(dir===-1&&s[0]%12===0)||s.includes(h)){stopSnake();return} s.unshift(h);if(h===f){do f=Math.floor(Math.random()*144);while(s.includes(f))}else s.pop();draw()},180)}
function g2048(){let a=Array(16).fill(0);a[5]=2;a[10]=2;let b=document.createElement('div');b.className='tiles';a.forEach(v=>{let x=document.createElement('div');x.className='tile';x.textContent=v||'';b.append(x)});let p=document.createElement('p');p.textContent='Versione arcade: tocca Nuovo numero per riempire la griglia.';let bt=document.createElement('button');bt.textContent='+ Nuovo numero';bt.onclick=()=>{let e=a.map((v,i)=>v?null:i).filter(v=>v!==null);if(!e.length)return;let i=e[Math.floor(Math.random()*e.length)];a[i]=Math.random()<.85?2:4;b.children[i].textContent=a[i]};area.append(b,p,bt)}
function quiz(){let qs=[['Quale porta è reversibile?',['USB-C','USB-A','VGA'],0],['Quanto fa 2+2?',['3','4','5'],1],['HTML serve principalmente per…',['Strutturare pagine','Caricare batterie','Riparare display'],0]],k=0,score=0;let render=()=>{area.innerHTML=`<div class=score>${score} punti</div><h3>${qs[k][0]}</h3>`;qs[k][1].forEach((x,i)=>{let b=document.createElement('button');b.textContent=x;b.style.margin='6px';b.onclick=()=>{if(i===qs[k][2])score++;k++;if(k>=qs.length){area.innerHTML=`<h2>Risultato: ${score}/${qs.length}</h2>`}else render()};area.append(b)})};render()}
function mini(n){area.innerHTML=`<div style='font-size:72px'>${n==='Car Race'?'🏎️':n==='Brick Breaker'?'🧱':'🛠️'}</div><h2>${n}</h2><p>Mini-sfida: premi il pulsante più volte in 10 secondi.</p><div class=score id=sc>0</div><button id=tap>TOCCA!</button>`;let s=0,on=true;area.querySelector('#tap').onclick=()=>{if(on)area.querySelector('#sc').textContent=++s};setTimeout(()=>{on=false;if(area.querySelector('#tap'))area.querySelector('#tap').textContent='Fine!'},10000)}
