(()=>{"use strict";
const c=document.getElementById('game'),x=c.getContext('2d'),D=Math.min(devicePixelRatio||1,2),E=id=>document.getElementById(id);
const start=E('start'),hud=E('hud'),controls=E('controls'),over=E('gameover'),msg=E('message');
const imgs={};['bg-race','bike','bike-left','bike-right','car-red','car-blue','car-yellow','truck','coin','ramp'].forEach(n=>{let i=new Image();i.src=n==='bg-race'?n+'.jpg':n+'.png';imgs[n]=i});
const aud={engine:new Audio('engine.wav'),coin:new Audio('coin.wav'),crash:new Audio('crash.wav'),turbo:new Audio('turbo.wav'),jump:new Audio('jump.wav'),checkpoint:new Audio('checkpoint.wav')};aud.engine.loop=true;aud.engine.volume=.22;
let W=innerWidth,H=innerHeight,playing=false,paused=false,last=0,raf=0,state;
function resize(){W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;x.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
function reset(){state={lane:1,laneX:1,lean:0,speed:90,targetSpeed:132,turbo:0,jump:0,jumpV:0,lives:3,score:0,level:1,progress:0,roadOffset:0,traffic:[],pickups:[],ramps:[],spawnT:0,coinT:0,rampT:0,invuln:0,shake:0,combo:0,comboT:0};updateHud()}
function updateHud(){E('score').textContent=Math.floor(state.score);E('lives').textContent=state.lives;E('level').textContent=state.level;E('speedNum').textContent=Math.floor(state.speed);E('progress').style.width=Math.min(100,state.progress)+'%'}
function banner(t){msg.textContent=t;msg.classList.remove('hidden');clearTimeout(banner.t);banner.t=setTimeout(()=>msg.classList.add('hidden'),1000)}
function sound(n){try{aud[n].currentTime=0;aud[n].play().catch(()=>{})}catch{}}
function refreshHome(){E('best').textContent=localStorage.motoRushBest||0;E('bestLevel').textContent=localStorage.motoRushLevel||1}refreshHome();
function startGame(){reset();start.classList.add('hidden');over.classList.add('hidden');hud.classList.remove('hidden');controls.classList.remove('hidden');playing=true;paused=false;last=performance.now();aud.engine.play().catch(()=>{});banner('🏁 VIA!');raf=requestAnimationFrame(loop)}
function gameOver(){playing=false;cancelAnimationFrame(raf);aud.engine.pause();hud.classList.add('hidden');controls.classList.add('hidden');over.classList.remove('hidden');let best=Math.max(+localStorage.motoRushBest||0,Math.floor(state.score));localStorage.motoRushBest=best;localStorage.motoRushLevel=Math.max(+localStorage.motoRushLevel||1,state.level);E('finalScore').textContent=Math.floor(state.score);E('finalLevel').textContent=state.level;E('finalBest').textContent=best;refreshHome()}
function lane(v){if(!playing||paused)return;state.lane=Math.max(0,Math.min(2,state.lane+v));state.lean=v;setTimeout(()=>state.lean=0,180)}
E('left').onpointerdown=()=>lane(-1);E('right').onpointerdown=()=>lane(1);E('jump').onpointerdown=()=>{if(playing&&!paused&&state.jump===0){state.jumpV=620;sound('jump')}};E('turbo').onpointerdown=()=>{if(playing&&!paused&&state.turbo<=0){state.turbo=2.2;sound('turbo');banner('⚡ TURBO!')}};E('brake').onpointerdown=()=>state.targetSpeed=72;E('brake').onpointerup=E('brake').onpointercancel=()=>state.targetSpeed=132+(state.level-1)*4;
E('play').onclick=startGame;E('again').onclick=startGame;E('home').onclick=()=>{over.classList.add('hidden');start.classList.remove('hidden')};E('how').onclick=()=>E('help').classList.remove('hidden');E('closeHelp').onclick=()=>E('help').classList.add('hidden');
E('pause').onclick=()=>{if(!playing)return;paused=!paused;E('pause').textContent=paused?'▶':'Ⅱ';if(paused){aud.engine.pause();banner('PAUSA')}else{aud.engine.play().catch(()=>{});last=performance.now();raf=requestAnimationFrame(loop)}};
addEventListener('keydown',e=>{if(e.key==='ArrowLeft')lane(-1);if(e.key==='ArrowRight')lane(1);if(e.key===' ')E('jump').onpointerdown();if(e.key==='Shift')E('turbo').onpointerdown()});
function roadAt(y){let horizon=H*.27,bottom=H*.98,t=(y-horizon)/(bottom-horizon);t=Math.max(0,Math.min(1,t));return{cx:W/2,half:W*(.13+.34*t),t}}
function lanePos(l,y){let r=roadAt(y);return r.cx+(l-1)*r.half*.62}function py(){return H*.80-state.jump*.22}
function spawnTraffic(){let types=['car-red','car-blue','car-yellow','truck'];state.traffic.push({lane:Math.floor(Math.random()*3),y:H*.29,type:types[Math.floor(Math.random()*types.length)],spd:58+Math.random()*38,passed:false})}
function spawnCoin(){let l=Math.floor(Math.random()*3);for(let k=0;k<4;k++)state.pickups.push({lane:l,y:H*.28-k*52,hit:false})}function spawnRamp(){state.ramps.push({lane:Math.floor(Math.random()*3),y:H*.30})}
function collide(l,y,range=48){return Math.abs(state.laneX-l)<.35&&Math.abs(py()-y)<range&&state.jump<90}
function crash(){if(state.invuln>0)return;state.lives--;state.invuln=1.55;state.shake=14;state.speed=Math.max(62,state.speed*.55);state.combo=0;sound('crash');banner('💥 ATTENTO!');if(state.lives<=0)setTimeout(gameOver,260)}
function checkpoint(){state.level++;state.progress=0;state.targetSpeed=Math.min(165,132+(state.level-1)*4);state.score+=500;sound('checkpoint');banner('🏁 CHECKPOINT '+state.level)}
function update(dt){let s=state;if(s.turbo>0){s.turbo-=dt;s.speed+=(220-s.speed)*dt*2.7}else s.speed+=(s.targetSpeed-s.speed)*dt*1.45;s.roadOffset+=s.speed*dt;s.score+=s.speed*dt*.18*(1+s.combo*.05);s.progress+=s.speed*dt*.0105;if(s.progress>=100)checkpoint();s.laneX+=(s.lane-s.laneX)*Math.min(1,dt*8);if(s.jumpV||s.jump>0){s.jumpV-=980*dt;s.jump+=s.jumpV*dt;if(s.jump<=0){s.jump=0;s.jumpV=0}}s.invuln=Math.max(0,s.invuln-dt);s.shake=Math.max(0,s.shake-dt*25);s.comboT-=dt;if(s.comboT<=0)s.combo=0;s.spawnT-=dt;s.coinT-=dt;s.rampT-=dt;if(s.spawnT<=0){spawnTraffic();s.spawnT=Math.max(.52,1.25-s.level*.055)+Math.random()*.7}if(s.coinT<=0){spawnCoin();s.coinT=2.3+Math.random()*2}if(s.rampT<=0){spawnRamp();s.rampT=5+Math.random()*5}let move=s.speed*dt*2.8;s.traffic.forEach(o=>{o.y+=move*(1.1-o.spd/220);if(collide(o.lane,o.y,58))crash();if(!o.passed&&o.y>py()+55){o.passed=true;s.score+=25}});s.traffic=s.traffic.filter(o=>o.y<H+160);s.pickups.forEach(o=>{o.y+=move;if(!o.hit&&collide(o.lane,o.y,45)){o.hit=true;s.combo++;s.comboT=2;s.score+=100*(1+s.combo*.1);sound('coin');if(s.combo>=5)banner('🔥 COMBO x'+s.combo)}});s.pickups=s.pickups.filter(o=>!o.hit&&o.y<H+80);s.ramps.forEach(o=>{o.y+=move;if(collide(o.lane,o.y,52)&&s.jump===0){s.jumpV=720;sound('jump');s.score+=150;banner('🛫 SALTO!')}});s.ramps=s.ramps.filter(o=>o.y<H+100);updateHud()}
function drawRoad(){let bg=imgs['bg-race'];if(bg.complete)x.drawImage(bg,0,0,W,H);else{x.fillStyle='#63bfea';x.fillRect(0,0,W,H)}let horizon=H*.27,bottom=H*1.03,wobble=Math.sin(state.roadOffset*.002)*W*.055,cx=W/2+wobble,top=W*.13,bot=W*.48;x.fillStyle='#343740';x.beginPath();x.moveTo(cx-top,horizon);x.lineTo(cx+top,horizon);x.lineTo(cx+bot,bottom);x.lineTo(cx-bot,bottom);x.closePath();x.fill();x.strokeStyle='#f2f0e8';x.lineWidth=4;x.beginPath();x.moveTo(cx-top,horizon);x.lineTo(cx-bot,bottom);x.moveTo(cx+top,horizon);x.lineTo(cx+bot,bottom);x.stroke();for(let ln=1;ln<3;ln++)for(let i=0;i<12;i++){let yy=horizon+((i*75+(state.roadOffset*1.8)%75)%(bottom-horizon)),r=roadAt(yy),xx=cx+(ln-1.5)*r.half*.62;x.strokeStyle='#ffffffcc';x.lineWidth=2+7*r.t;x.beginPath();x.moveTo(xx,yy);x.lineTo(xx,yy+18+40*r.t);x.stroke()}}
function obj(name,l,y,bw,bh){let r=roadAt(y),sc=.25+r.t*1.1,iw=bw*sc,ih=bh*sc,xx=lanePos(l,y)-iw/2;if(imgs[name].complete)x.drawImage(imgs[name],xx,y-ih/2,iw,ih)}
function render(){x.save();if(state.shake)x.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);drawRoad();state.pickups.forEach(o=>obj('coin',o.lane,o.y,80,80));state.ramps.forEach(o=>obj('ramp',o.lane,o.y,150,100));[...state.traffic].sort((a,b)=>a.y-b.y).forEach(o=>obj(o.type,o.lane,o.y,150,o.type==='truck'?230:210));let yy=py(),px=lanePos(state.laneX,yy),spr=state.lean<0?imgs['bike-left']:state.lean>0?imgs['bike-right']:imgs['bike'],bw=Math.min(150,W*.13),bh=bw*1.42;if(state.turbo>0){x.fillStyle='#4ed9ff99';x.beginPath();x.moveTo(px-18,yy+bh*.28);x.lineTo(px,yy+bh*.75);x.lineTo(px+18,yy+bh*.28);x.fill()}if(spr.complete){x.globalAlpha=state.invuln>0&&Math.floor(state.invuln*12)%2?.4:1;x.drawImage(spr,px-bw/2,yy-bh/2,bw,bh);x.globalAlpha=1}if(state.jump>0){x.fillStyle='#0006';x.beginPath();x.ellipse(px,H*.86,bw*.42,bw*.12,0,0,Math.PI*2);x.fill()}x.restore()}
function loop(t){if(!playing||paused)return;let dt=Math.min(.035,(t-last)/1000||.016);last=t;update(dt);render();raf=requestAnimationFrame(loop)}
reset();render();
})();
